# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct MasterDataApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `MasterDataApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ MasterDataApi }) = "https://web-api.tp.entsoe.eu/api"

const _returntypes_master_data_production_and_generation_units_MasterDataApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_master_data_production_and_generation_units(_api::MasterDataApi, document_type::String, business_type::String, bidding_zone_domain::String, implementation_date_and_or_time::String; psr_type=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_master_data_production_and_generation_units_MasterDataApi, "/master-data/production-and-generation-units", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "BiddingZone_Domain", bidding_zone_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Implementation_DateAndOrTime", implementation_date_and_or_time; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "psrType", psr_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Production and Generation Units

> Response contains commissioned production units for given day

Params:
- document_type::String (required)
- business_type::String (required)
- bidding_zone_domain::String (required)
- implementation_date_and_or_time::String (required)
- psr_type::String

Return: String, OpenAPI.Clients.ApiResponse
"""
function master_data_production_and_generation_units(_api::MasterDataApi, document_type::String, business_type::String, bidding_zone_domain::String, implementation_date_and_or_time::String; psr_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_master_data_production_and_generation_units(_api, document_type, business_type, bidding_zone_domain, implementation_date_and_or_time; psr_type=psr_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function master_data_production_and_generation_units(_api::MasterDataApi, response_stream::Channel, document_type::String, business_type::String, bidding_zone_domain::String, implementation_date_and_or_time::String; psr_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_master_data_production_and_generation_units(_api, document_type, business_type, bidding_zone_domain, implementation_date_and_or_time; psr_type=psr_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export master_data_production_and_generation_units
