# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct GenerationApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `GenerationApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ GenerationApi }) = "https://web-api.tp.entsoe.eu/api"

const _returntypes_generation141_a_installed_capacity_per_production_type_GenerationApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_generation141_a_installed_capacity_per_production_type(_api::GenerationApi, document_type::String, process_type::String, in_domain::String, period_start::Int64, period_end::Int64; psr_type=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_generation141_a_installed_capacity_per_production_type_GenerationApi, "/generation/14-1-a-installed-capacity-per-production-type", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "PsrType", psr_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""14.1.A Installed Capacity per Production Type

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- process_type::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- psr_type::String

Return: String, OpenAPI.Clients.ApiResponse
"""
function generation141_a_installed_capacity_per_production_type(_api::GenerationApi, document_type::String, process_type::String, in_domain::String, period_start::Int64, period_end::Int64; psr_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_generation141_a_installed_capacity_per_production_type(_api, document_type, process_type, in_domain, period_start, period_end; psr_type=psr_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function generation141_a_installed_capacity_per_production_type(_api::GenerationApi, response_stream::Channel, document_type::String, process_type::String, in_domain::String, period_start::Int64, period_end::Int64; psr_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_generation141_a_installed_capacity_per_production_type(_api, document_type, process_type, in_domain, period_start, period_end; psr_type=psr_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_generation141_b_installed_capacity_per_production_unit_GenerationApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_generation141_b_installed_capacity_per_production_unit(_api::GenerationApi, document_type::String, process_type::String, in_domain::String, period_start::Int64, period_end::Int64; psr_type=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_generation141_b_installed_capacity_per_production_unit_GenerationApi, "/generation/14-1-b-installed-capacity-per-production-unit", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "PsrType", psr_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""14.1.B Installed Capacity Per Production Unit

Params:
- document_type::String (required)
- process_type::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- psr_type::String

Return: String, OpenAPI.Clients.ApiResponse
"""
function generation141_b_installed_capacity_per_production_unit(_api::GenerationApi, document_type::String, process_type::String, in_domain::String, period_start::Int64, period_end::Int64; psr_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_generation141_b_installed_capacity_per_production_unit(_api, document_type, process_type, in_domain, period_start, period_end; psr_type=psr_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function generation141_b_installed_capacity_per_production_unit(_api::GenerationApi, response_stream::Channel, document_type::String, process_type::String, in_domain::String, period_start::Int64, period_end::Int64; psr_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_generation141_b_installed_capacity_per_production_unit(_api, document_type, process_type, in_domain, period_start, period_end; psr_type=psr_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_generation141_c_generation_forecast_day_ahead_GenerationApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_generation141_c_generation_forecast_day_ahead(_api::GenerationApi, document_type::String, process_type::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_generation141_c_generation_forecast_day_ahead_GenerationApi, "/generation/14-1-c-generation-forecast-day-ahead", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""14.1.C Generation Forecast - Day ahead

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.  Time series with inBiddingZone_Domain attribute reflects Generation values while outBiddingZone_Domain reflects Consumption values.

Params:
- document_type::String (required)
- process_type::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function generation141_c_generation_forecast_day_ahead(_api::GenerationApi, document_type::String, process_type::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_generation141_c_generation_forecast_day_ahead(_api, document_type, process_type, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function generation141_c_generation_forecast_day_ahead(_api::GenerationApi, response_stream::Channel, document_type::String, process_type::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_generation141_c_generation_forecast_day_ahead(_api, document_type, process_type, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_generation141_d_generation_forecasts_for_wind_and_solar_GenerationApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_generation141_d_generation_forecasts_for_wind_and_solar(_api::GenerationApi, document_type::String, process_type::String, in_domain::String, period_start::Int64, period_end::Int64; psr_type=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_generation141_d_generation_forecasts_for_wind_and_solar_GenerationApi, "/generation/14-1-d-generation-forecasts-for-wind-and-solar", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "PsrType", psr_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""14.1.D Generation Forecasts for Wind and Solar

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- process_type::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- psr_type::String

Return: String, OpenAPI.Clients.ApiResponse
"""
function generation141_d_generation_forecasts_for_wind_and_solar(_api::GenerationApi, document_type::String, process_type::String, in_domain::String, period_start::Int64, period_end::Int64; psr_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_generation141_d_generation_forecasts_for_wind_and_solar(_api, document_type, process_type, in_domain, period_start, period_end; psr_type=psr_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function generation141_d_generation_forecasts_for_wind_and_solar(_api::GenerationApi, response_stream::Channel, document_type::String, process_type::String, in_domain::String, period_start::Int64, period_end::Int64; psr_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_generation141_d_generation_forecasts_for_wind_and_solar(_api, document_type, process_type, in_domain, period_start, period_end; psr_type=psr_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_generation161_a_actual_generation_per_generation_unit_GenerationApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_generation161_a_actual_generation_per_generation_unit(_api::GenerationApi, document_type::String, process_type::String, in_domain::String, period_start::Int64, period_end::Int64; psr_type=nothing, registered_resource=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_generation161_a_actual_generation_per_generation_unit_GenerationApi, "/generation/16-1-a-actual-generation-per-generation-unit", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "PsrType", psr_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "RegisteredResource", registered_resource; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""16.1.A Actual Generation per Generation Unit

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 day.  **Important notes:**  - Response from API is same irrespective of querying for Document Types A74 - Wind & Solar & A75 - Actual Generation Per Type      - Time series with inBiddingZone_Domain attribute reflects **generation** values while outBiddingZone_Domain reflects **consumption** values.

Params:
- document_type::String (required)
- process_type::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- psr_type::String
- registered_resource::String

Return: String, OpenAPI.Clients.ApiResponse
"""
function generation161_a_actual_generation_per_generation_unit(_api::GenerationApi, document_type::String, process_type::String, in_domain::String, period_start::Int64, period_end::Int64; psr_type=nothing, registered_resource=nothing, _mediaType=nothing)
    _ctx = _oacinternal_generation161_a_actual_generation_per_generation_unit(_api, document_type, process_type, in_domain, period_start, period_end; psr_type=psr_type, registered_resource=registered_resource, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function generation161_a_actual_generation_per_generation_unit(_api::GenerationApi, response_stream::Channel, document_type::String, process_type::String, in_domain::String, period_start::Int64, period_end::Int64; psr_type=nothing, registered_resource=nothing, _mediaType=nothing)
    _ctx = _oacinternal_generation161_a_actual_generation_per_generation_unit(_api, document_type, process_type, in_domain, period_start, period_end; psr_type=psr_type, registered_resource=registered_resource, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_generation161_b_c_actual_generation_per_production_type_GenerationApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_generation161_b_c_actual_generation_per_production_type(_api::GenerationApi, document_type::String, process_type::String, in_domain::String, period_start::Int64, period_end::Int64; psr_type=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_generation161_b_c_actual_generation_per_production_type_GenerationApi, "/generation/16-1-b-c-actual-generation-per-production-type", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "psrType", psr_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""16.1.B&C Actual Generation per Production Type

<u><b>Request limit</b></u>: Each request may cover a period of up to 1 year.  Response from API is same irrespective of querying for Document Types A74 - Wind & Solar & A75 - Actual Generation Per Type  Time series with inBiddingZone_Domain attribute reflects Generation values while outBiddingZone_Domain reflects Consumption values.**

Params:
- document_type::String (required)
- process_type::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- psr_type::String

Return: String, OpenAPI.Clients.ApiResponse
"""
function generation161_b_c_actual_generation_per_production_type(_api::GenerationApi, document_type::String, process_type::String, in_domain::String, period_start::Int64, period_end::Int64; psr_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_generation161_b_c_actual_generation_per_production_type(_api, document_type, process_type, in_domain, period_start, period_end; psr_type=psr_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function generation161_b_c_actual_generation_per_production_type(_api::GenerationApi, response_stream::Channel, document_type::String, process_type::String, in_domain::String, period_start::Int64, period_end::Int64; psr_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_generation161_b_c_actual_generation_per_production_type(_api, document_type, process_type, in_domain, period_start, period_end; psr_type=psr_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_generation161_d_water_reservoirs_and_hydro_storage_plants_GenerationApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_generation161_d_water_reservoirs_and_hydro_storage_plants(_api::GenerationApi, document_type::String, process_type::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_generation161_d_water_reservoirs_and_hydro_storage_plants_GenerationApi, "/generation/16-1-d-water-reservoirs-and-hydro-storage-plants", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""16.1.D Water Reservoirs and Hydro Storage Plants

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- process_type::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function generation161_d_water_reservoirs_and_hydro_storage_plants(_api::GenerationApi, document_type::String, process_type::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_generation161_d_water_reservoirs_and_hydro_storage_plants(_api, document_type, process_type, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function generation161_d_water_reservoirs_and_hydro_storage_plants(_api::GenerationApi, response_stream::Channel, document_type::String, process_type::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_generation161_d_water_reservoirs_and_hydro_storage_plants(_api, document_type, process_type, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export generation141_a_installed_capacity_per_production_type
export generation141_b_installed_capacity_per_production_unit
export generation141_c_generation_forecast_day_ahead
export generation141_d_generation_forecasts_for_wind_and_solar
export generation161_a_actual_generation_per_generation_unit
export generation161_b_c_actual_generation_per_production_type
export generation161_d_water_reservoirs_and_hydro_storage_plants
