# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct LoadApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `LoadApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ LoadApi }) = "https://web-api.tp.entsoe.eu/api"

const _returntypes_load61_a_actual_total_load_LoadApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_load61_a_actual_total_load(_api::LoadApi, document_type::String, process_type::String, out_bidding_zone_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_load61_a_actual_total_load_LoadApi, "/load/6-1-a-actual-total-load", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "outBiddingZone_Domain", out_bidding_zone_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""6.1.A Actual Total Load

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- process_type::String (required)
- out_bidding_zone_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function load61_a_actual_total_load(_api::LoadApi, document_type::String, process_type::String, out_bidding_zone_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_load61_a_actual_total_load(_api, document_type, process_type, out_bidding_zone_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function load61_a_actual_total_load(_api::LoadApi, response_stream::Channel, document_type::String, process_type::String, out_bidding_zone_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_load61_a_actual_total_load(_api, document_type, process_type, out_bidding_zone_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_load61_a_actual_total_load_post_LoadApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_load61_a_actual_total_load_post(_api::LoadApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_load61_a_actual_total_load_post_LoadApi, "/load/6-1-a-actual-total-load-post", ["SecurityToken", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""6.1.A Actual Total Load (Post)

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:

Return: String, OpenAPI.Clients.ApiResponse
"""
function load61_a_actual_total_load_post(_api::LoadApi; _mediaType=nothing)
    _ctx = _oacinternal_load61_a_actual_total_load_post(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function load61_a_actual_total_load_post(_api::LoadApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_load61_a_actual_total_load_post(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_load61_a_actual_total_load_security_token_in_header_LoadApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_load61_a_actual_total_load_security_token_in_header(_api::LoadApi, document_type::String, process_type::String, out_bidding_zone_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_load61_a_actual_total_load_security_token_in_header_LoadApi, "/load/6-1-a-actual-total-load-security-token-in-header", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "outBiddingZone_Domain", out_bidding_zone_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""6.1.A Actual Total Load - SECURITY_TOKEN in header

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.  **Note**: This is an example where the security token is included in the request header rather than in the query parameters.

Params:
- document_type::String (required)
- process_type::String (required)
- out_bidding_zone_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function load61_a_actual_total_load_security_token_in_header(_api::LoadApi, document_type::String, process_type::String, out_bidding_zone_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_load61_a_actual_total_load_security_token_in_header(_api, document_type, process_type, out_bidding_zone_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function load61_a_actual_total_load_security_token_in_header(_api::LoadApi, response_stream::Channel, document_type::String, process_type::String, out_bidding_zone_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_load61_a_actual_total_load_security_token_in_header(_api, document_type, process_type, out_bidding_zone_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_load61_b_day_ahead_total_load_forecast_LoadApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_load61_b_day_ahead_total_load_forecast(_api::LoadApi, document_type::String, process_type::String, out_bidding_zone_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_load61_b_day_ahead_total_load_forecast_LoadApi, "/load/6-1-b-day-ahead-total-load-forecast", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "outBiddingZone_Domain", out_bidding_zone_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""6.1.B Day-ahead Total Load Forecast

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- process_type::String (required)
- out_bidding_zone_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function load61_b_day_ahead_total_load_forecast(_api::LoadApi, document_type::String, process_type::String, out_bidding_zone_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_load61_b_day_ahead_total_load_forecast(_api, document_type, process_type, out_bidding_zone_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function load61_b_day_ahead_total_load_forecast(_api::LoadApi, response_stream::Channel, document_type::String, process_type::String, out_bidding_zone_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_load61_b_day_ahead_total_load_forecast(_api, document_type, process_type, out_bidding_zone_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_load61_c_week_ahead_total_load_forecast_LoadApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_load61_c_week_ahead_total_load_forecast(_api::LoadApi, document_type::String, process_type::String, out_bidding_zone_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_load61_c_week_ahead_total_load_forecast_LoadApi, "/load/6-1-c-week-ahead-total-load-forecast", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "outBiddingZone_Domain", out_bidding_zone_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""6.1.C Week-ahead Total Load Forecast

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- process_type::String (required)
- out_bidding_zone_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function load61_c_week_ahead_total_load_forecast(_api::LoadApi, document_type::String, process_type::String, out_bidding_zone_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_load61_c_week_ahead_total_load_forecast(_api, document_type, process_type, out_bidding_zone_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function load61_c_week_ahead_total_load_forecast(_api::LoadApi, response_stream::Channel, document_type::String, process_type::String, out_bidding_zone_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_load61_c_week_ahead_total_load_forecast(_api, document_type, process_type, out_bidding_zone_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_load61_d_month_ahead_total_load_forecast_LoadApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_load61_d_month_ahead_total_load_forecast(_api::LoadApi, document_type::String, process_type::String, out_bidding_zone_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_load61_d_month_ahead_total_load_forecast_LoadApi, "/load/6-1-d-month-ahead-total-load-forecast", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "outBiddingZone_Domain", out_bidding_zone_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""6.1.D Month-ahead Total Load Forecast

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- process_type::String (required)
- out_bidding_zone_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function load61_d_month_ahead_total_load_forecast(_api::LoadApi, document_type::String, process_type::String, out_bidding_zone_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_load61_d_month_ahead_total_load_forecast(_api, document_type, process_type, out_bidding_zone_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function load61_d_month_ahead_total_load_forecast(_api::LoadApi, response_stream::Channel, document_type::String, process_type::String, out_bidding_zone_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_load61_d_month_ahead_total_load_forecast(_api, document_type, process_type, out_bidding_zone_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_load61_e_year_ahead_total_load_forecast_LoadApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_load61_e_year_ahead_total_load_forecast(_api::LoadApi, document_type::String, process_type::String, out_bidding_zone_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_load61_e_year_ahead_total_load_forecast_LoadApi, "/load/6-1-e-year-ahead-total-load-forecast", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "outBiddingZone_Domain", out_bidding_zone_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""6.1.E Year-ahead Total Load Forecast

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- process_type::String (required)
- out_bidding_zone_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function load61_e_year_ahead_total_load_forecast(_api::LoadApi, document_type::String, process_type::String, out_bidding_zone_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_load61_e_year_ahead_total_load_forecast(_api, document_type, process_type, out_bidding_zone_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function load61_e_year_ahead_total_load_forecast(_api::LoadApi, response_stream::Channel, document_type::String, process_type::String, out_bidding_zone_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_load61_e_year_ahead_total_load_forecast(_api, document_type, process_type, out_bidding_zone_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_load81_year_ahead_forecast_margin_LoadApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_load81_year_ahead_forecast_margin(_api::LoadApi, document_type::String, process_type::String, out_bidding_zone_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_load81_year_ahead_forecast_margin_LoadApi, "/load/8-1-year-ahead-forecast-margin", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "outBiddingZone_Domain", out_bidding_zone_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""8.1 Year-ahead Forecast Margin

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- process_type::String (required)
- out_bidding_zone_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function load81_year_ahead_forecast_margin(_api::LoadApi, document_type::String, process_type::String, out_bidding_zone_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_load81_year_ahead_forecast_margin(_api, document_type, process_type, out_bidding_zone_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function load81_year_ahead_forecast_margin(_api::LoadApi, response_stream::Channel, document_type::String, process_type::String, out_bidding_zone_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_load81_year_ahead_forecast_margin(_api, document_type, process_type, out_bidding_zone_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export load61_a_actual_total_load
export load61_a_actual_total_load_post
export load61_a_actual_total_load_security_token_in_header
export load61_b_day_ahead_total_load_forecast
export load61_c_week_ahead_total_load_forecast
export load61_d_month_ahead_total_load_forecast
export load61_e_year_ahead_total_load_forecast
export load81_year_ahead_forecast_margin
