# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct TransmissionApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `TransmissionApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ TransmissionApi }) = "https://web-api.tp.entsoe.eu/api"

const _returntypes_transmission111_a_forecasted_transfer_capacities_TransmissionApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_transmission111_a_forecasted_transfer_capacities(_api::TransmissionApi, document_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_transmission111_a_forecasted_transfer_capacities_TransmissionApi, "/transmission/11-1-a-forecasted-transfer-capacities", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "contract_MarketAgreement.Type", contract_market_agreement_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""11.1.A Forecasted Transfer Capacities

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- contract_market_agreement_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function transmission111_a_forecasted_transfer_capacities(_api::TransmissionApi, document_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_transmission111_a_forecasted_transfer_capacities(_api, document_type, contract_market_agreement_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function transmission111_a_forecasted_transfer_capacities(_api::TransmissionApi, response_stream::Channel, document_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_transmission111_a_forecasted_transfer_capacities(_api, document_type, contract_market_agreement_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_transmission113_cross_border_capacity_of_dc_links_intraday_transfer_limits_TransmissionApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_transmission113_cross_border_capacity_of_dc_links_intraday_transfer_limits(_api::TransmissionApi, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_transmission113_cross_border_capacity_of_dc_links_intraday_transfer_limits_TransmissionApi, "/transmission/11-3-cross-border-capacity-of-dc-links-intraday-transfer-limits", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""11.3 Cross Border Capacity of DC Links - Intraday Transfer Limits

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements is returned per XML response.

Params:
- document_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function transmission113_cross_border_capacity_of_dc_links_intraday_transfer_limits(_api::TransmissionApi, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_transmission113_cross_border_capacity_of_dc_links_intraday_transfer_limits(_api, document_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function transmission113_cross_border_capacity_of_dc_links_intraday_transfer_limits(_api::TransmissionApi, response_stream::Channel, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_transmission113_cross_border_capacity_of_dc_links_intraday_transfer_limits(_api, document_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_transmission121_f_commercial_schedules_TransmissionApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_transmission121_f_commercial_schedules(_api::TransmissionApi, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; contract_market_agreement_type=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_transmission121_f_commercial_schedules_TransmissionApi, "/transmission/12-1-f-commercial-schedules", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "contract_MarketAgreement.Type", contract_market_agreement_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""12.1.F Commercial Schedules

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- contract_market_agreement_type::String

Return: String, OpenAPI.Clients.ApiResponse
"""
function transmission121_f_commercial_schedules(_api::TransmissionApi, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; contract_market_agreement_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_transmission121_f_commercial_schedules(_api, document_type, out_domain, in_domain, period_start, period_end; contract_market_agreement_type=contract_market_agreement_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function transmission121_f_commercial_schedules(_api::TransmissionApi, response_stream::Channel, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; contract_market_agreement_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_transmission121_f_commercial_schedules(_api, document_type, out_domain, in_domain, period_start, period_end; contract_market_agreement_type=contract_market_agreement_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_transmission121_f_commercial_schedules_net_positions_TransmissionApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_transmission121_f_commercial_schedules_net_positions(_api::TransmissionApi, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; contract_market_agreement_type=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_transmission121_f_commercial_schedules_net_positions_TransmissionApi, "/transmission/12-1-f-commercial-schedules-net-positions", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "contract_MarketAgreement.Type", contract_market_agreement_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""12.1.F Commercial Schedules - Net Positions

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- contract_market_agreement_type::String

Return: String, OpenAPI.Clients.ApiResponse
"""
function transmission121_f_commercial_schedules_net_positions(_api::TransmissionApi, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; contract_market_agreement_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_transmission121_f_commercial_schedules_net_positions(_api, document_type, out_domain, in_domain, period_start, period_end; contract_market_agreement_type=contract_market_agreement_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function transmission121_f_commercial_schedules_net_positions(_api::TransmissionApi, response_stream::Channel, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; contract_market_agreement_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_transmission121_f_commercial_schedules_net_positions(_api, document_type, out_domain, in_domain, period_start, period_end; contract_market_agreement_type=contract_market_agreement_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_transmission121_g_cross_border_physical_flows_TransmissionApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_transmission121_g_cross_border_physical_flows(_api::TransmissionApi, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_transmission121_g_cross_border_physical_flows_TransmissionApi, "/transmission/12-1-g-cross-border-physical-flows", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""12.1.G Cross-Border Physical Flows

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.  Unlike Web GUI, API responds not netted values as data is requested per direction.

Params:
- document_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function transmission121_g_cross_border_physical_flows(_api::TransmissionApi, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_transmission121_g_cross_border_physical_flows(_api, document_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function transmission121_g_cross_border_physical_flows(_api::TransmissionApi, response_stream::Channel, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_transmission121_g_cross_border_physical_flows(_api, document_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_transmission131_a_redispatching_cross_border_TransmissionApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_transmission131_a_redispatching_cross_border(_api::TransmissionApi, document_type::String, business_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_transmission131_a_redispatching_cross_border_TransmissionApi, "/transmission/13-1-a-redispatching-cross-border", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""13.1.A Redispatching Cross Border

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements is returned per XML response.

Params:
- document_type::String (required)
- business_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function transmission131_a_redispatching_cross_border(_api::TransmissionApi, document_type::String, business_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_transmission131_a_redispatching_cross_border(_api, document_type, business_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function transmission131_a_redispatching_cross_border(_api::TransmissionApi, response_stream::Channel, document_type::String, business_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_transmission131_a_redispatching_cross_border(_api, document_type, business_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_transmission131_a_redispatching_internal_TransmissionApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_transmission131_a_redispatching_internal(_api::TransmissionApi, document_type::String, business_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_transmission131_a_redispatching_internal_TransmissionApi, "/transmission/13-1-a-redispatching-internal", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""13.1.A Redispatching Internal

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements is returned per XML response.

Params:
- document_type::String (required)
- business_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function transmission131_a_redispatching_internal(_api::TransmissionApi, document_type::String, business_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_transmission131_a_redispatching_internal(_api, document_type, business_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function transmission131_a_redispatching_internal(_api::TransmissionApi, response_stream::Channel, document_type::String, business_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_transmission131_a_redispatching_internal(_api, document_type, business_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_transmission131_b_countertrading_TransmissionApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_transmission131_b_countertrading(_api::TransmissionApi, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_transmission131_b_countertrading_TransmissionApi, "/transmission/13-1-b-countertrading", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""13.1.B Countertrading

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements is returned per XML response.

Params:
- document_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function transmission131_b_countertrading(_api::TransmissionApi, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_transmission131_b_countertrading(_api, document_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function transmission131_b_countertrading(_api::TransmissionApi, response_stream::Channel, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_transmission131_b_countertrading(_api, document_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_transmission131_c_costs_of_congestion_management_TransmissionApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_transmission131_c_costs_of_congestion_management(_api::TransmissionApi, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_transmission131_c_costs_of_congestion_management_TransmissionApi, "/transmission/13-1-c-costs-of-congestion-management", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""13.1.C Costs of Congestion Management

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function transmission131_c_costs_of_congestion_management(_api::TransmissionApi, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_transmission131_c_costs_of_congestion_management(_api, document_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function transmission131_c_costs_of_congestion_management(_api::TransmissionApi, response_stream::Channel, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_transmission131_c_costs_of_congestion_management(_api, document_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_transmission91_expansion_and_dismantling_project_TransmissionApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_transmission91_expansion_and_dismantling_project(_api::TransmissionApi, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, doc_status=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_transmission91_expansion_and_dismantling_project_TransmissionApi, "/transmission/9-1-expansion-and-dismantling-project", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "DocStatus", doc_status; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""9.1 Expansion and Dismantling Project

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements is returned per XML response.

Params:
- document_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- business_type::String
- doc_status::String

Return: String, OpenAPI.Clients.ApiResponse
"""
function transmission91_expansion_and_dismantling_project(_api::TransmissionApi, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, doc_status=nothing, _mediaType=nothing)
    _ctx = _oacinternal_transmission91_expansion_and_dismantling_project(_api, document_type, out_domain, in_domain, period_start, period_end; business_type=business_type, doc_status=doc_status, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function transmission91_expansion_and_dismantling_project(_api::TransmissionApi, response_stream::Channel, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, doc_status=nothing, _mediaType=nothing)
    _ctx = _oacinternal_transmission91_expansion_and_dismantling_project(_api, document_type, out_domain, in_domain, period_start, period_end; business_type=business_type, doc_status=doc_status, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export transmission111_a_forecasted_transfer_capacities
export transmission113_cross_border_capacity_of_dc_links_intraday_transfer_limits
export transmission121_f_commercial_schedules
export transmission121_f_commercial_schedules_net_positions
export transmission121_g_cross_border_physical_flows
export transmission131_a_redispatching_cross_border
export transmission131_a_redispatching_internal
export transmission131_b_countertrading
export transmission131_c_costs_of_congestion_management
export transmission91_expansion_and_dismantling_project
