# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct BalancingApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `BalancingApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ BalancingApi }) = "https://web-api.tp.entsoe.eu/api"

const _returntypes_balancing123_a_current_balancing_state_gl_eb_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing123_a_current_balancing_state_gl_eb(_api::BalancingApi, document_type::String, business_type::String, area_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing123_a_current_balancing_state_gl_eb_BalancingApi, "/balancing/12-3-a-current-balancing-state-gl-eb", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "area_Domain", area_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""12.3.A Current balancing state [GL EB]

<u><b>Request limit:</b></u> Each request may cover a period of up to 100 days.

Params:
- document_type::String (required)
- business_type::String (required)
- area_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing123_a_current_balancing_state_gl_eb(_api::BalancingApi, document_type::String, business_type::String, area_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_balancing123_a_current_balancing_state_gl_eb(_api, document_type, business_type, area_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing123_a_current_balancing_state_gl_eb(_api::BalancingApi, response_stream::Channel, document_type::String, business_type::String, area_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_balancing123_a_current_balancing_state_gl_eb(_api, document_type, business_type, area_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing123_b_c_balancing_energy_bids_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing123_b_c_balancing_energy_bids(_api::BalancingApi, document_type::String, business_type::String, process_type::String, connecting_domain::String, period_start::Int64, period_end::Int64; offset=nothing, standard_market_product=nothing, original_market_product=nothing, direction=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing123_b_c_balancing_energy_bids_BalancingApi, "/balancing/12-3-b-c-balancing-energy-bids", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "connecting_Domain", connecting_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Standard_MarketProduct", standard_market_product; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Original_MarketProduct", original_market_product; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Direction", direction; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""12.3.B&C Balancing energy bids

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements in total, counted across all XML documents contained in the ZIP response. The `offset`parameter can be used to retrieve the data in batches of up to 100 TimeSeries, where `offset=0` returns the first 100 elements, `offset=100` returns the next 100, and so on.

Params:
- document_type::String (required)
- business_type::String (required)
- process_type::String (required)
- connecting_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- offset::Int64
- standard_market_product::String
- original_market_product::String
- direction::String

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing123_b_c_balancing_energy_bids(_api::BalancingApi, document_type::String, business_type::String, process_type::String, connecting_domain::String, period_start::Int64, period_end::Int64; offset=nothing, standard_market_product=nothing, original_market_product=nothing, direction=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing123_b_c_balancing_energy_bids(_api, document_type, business_type, process_type, connecting_domain, period_start, period_end; offset=offset, standard_market_product=standard_market_product, original_market_product=original_market_product, direction=direction, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing123_b_c_balancing_energy_bids(_api::BalancingApi, response_stream::Channel, document_type::String, business_type::String, process_type::String, connecting_domain::String, period_start::Int64, period_end::Int64; offset=nothing, standard_market_product=nothing, original_market_product=nothing, direction=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing123_b_c_balancing_energy_bids(_api, document_type, business_type, process_type, connecting_domain, period_start, period_end; offset=offset, standard_market_product=standard_market_product, original_market_product=original_market_product, direction=direction, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing123_b_c_balancing_energy_bids_archives_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing123_b_c_balancing_energy_bids_archives(_api::BalancingApi, document_type::String, business_type::String, process_type::String, connecting_domain::String, period_start::Int64, period_end::Int64, storage_type::String; offset=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing123_b_c_balancing_energy_bids_archives_BalancingApi, "/balancing/12-3-b-c-balancing-energy-bids-archives", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "connecting_Domain", connecting_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "storageType", storage_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""12.3.B&C Balancing energy bids archives

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 ZIP files contained in the ZIP response. The `offset`parameter can be used to retrieve the data in batches of up to 100 ZIP archives, where`offset=0` returns the first 100 archives, `offset=100` returns the next 100, and so on.

Params:
- document_type::String (required)
- business_type::String (required)
- process_type::String (required)
- connecting_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- storage_type::String (required)
- offset::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing123_b_c_balancing_energy_bids_archives(_api::BalancingApi, document_type::String, business_type::String, process_type::String, connecting_domain::String, period_start::Int64, period_end::Int64, storage_type::String; offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing123_b_c_balancing_energy_bids_archives(_api, document_type, business_type, process_type, connecting_domain, period_start, period_end, storage_type; offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing123_b_c_balancing_energy_bids_archives(_api::BalancingApi, response_stream::Channel, document_type::String, business_type::String, process_type::String, connecting_domain::String, period_start::Int64, period_end::Int64, storage_type::String; offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing123_b_c_balancing_energy_bids_archives(_api, document_type, business_type, process_type, connecting_domain, period_start, period_end, storage_type; offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing123_e_aggregated_balancing_energy_bids_gl_eb_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing123_e_aggregated_balancing_energy_bids_gl_eb(_api::BalancingApi, document_type::String, process_type::String, area_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing123_e_aggregated_balancing_energy_bids_gl_eb_BalancingApi, "/balancing/12-3-e-aggregated-balancing-energy-bids-gl-eb", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "area_Domain", area_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""12.3.E Aggregated Balancing Energy Bids (GL EB)

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- process_type::String (required)
- area_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing123_e_aggregated_balancing_energy_bids_gl_eb(_api::BalancingApi, document_type::String, process_type::String, area_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_balancing123_e_aggregated_balancing_energy_bids_gl_eb(_api, document_type, process_type, area_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing123_e_aggregated_balancing_energy_bids_gl_eb(_api::BalancingApi, response_stream::Channel, document_type::String, process_type::String, area_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_balancing123_e_aggregated_balancing_energy_bids_gl_eb(_api, document_type, process_type, area_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing123_f_procured_balancing_capacity_gl_eb_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing123_f_procured_balancing_capacity_gl_eb(_api::BalancingApi, document_type::String, process_type::String, area_domain::String, period_start::Int64; period_end=nothing, offset=nothing, type_market_agreement_type=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing123_f_procured_balancing_capacity_gl_eb_BalancingApi, "/balancing/12-3-f-procured-balancing-capacity-gl-eb", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "area_Domain", area_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Type_MarketAgreement.Type", type_market_agreement_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""12.3.F Procured balancing capacity (GL EB)

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements in total, counted across all XML documents contained in the ZIP response. The `offset`parameter can be used to retrieve the data in batches of up to 100 TimeSeries, where `offset=0` returns the first 100 elements, `offset=100` returns the next 100, and so on.

Params:
- document_type::String (required)
- process_type::String (required)
- area_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64
- offset::Int64
- type_market_agreement_type::String

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing123_f_procured_balancing_capacity_gl_eb(_api::BalancingApi, document_type::String, process_type::String, area_domain::String, period_start::Int64; period_end=nothing, offset=nothing, type_market_agreement_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing123_f_procured_balancing_capacity_gl_eb(_api, document_type, process_type, area_domain, period_start; period_end=period_end, offset=offset, type_market_agreement_type=type_market_agreement_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing123_f_procured_balancing_capacity_gl_eb(_api::BalancingApi, response_stream::Channel, document_type::String, process_type::String, area_domain::String, period_start::Int64; period_end=nothing, offset=nothing, type_market_agreement_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing123_f_procured_balancing_capacity_gl_eb(_api, document_type, process_type, area_domain, period_start; period_end=period_end, offset=offset, type_market_agreement_type=type_market_agreement_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing123_h_i_allocation_and_use_of_cross_zonal_balancing_capacity_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing123_h_i_allocation_and_use_of_cross_zonal_balancing_capacity(_api::BalancingApi, document_type::String, process_type::String, connecting_domain::String, acquiring_domain::String, period_start::Int64, period_end::Int64; type_market_agreement_type=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing123_h_i_allocation_and_use_of_cross_zonal_balancing_capacity_BalancingApi, "/balancing/12-3-h-i-allocation-and-use-of-cross-zonal-balancing-capacity", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Connecting_Domain", connecting_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Acquiring_Domain", acquiring_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Type_MarketAgreement.Type", type_market_agreement_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""12.3.H&I Allocation and use of cross-zonal balancing capacity

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 instances contained in the ZIP response. One instance can be split into up to 8 TimeSeries. The total number of files in the ZIP file is variable and depends on the values of the dividing elements - allocation decision time, domain.mRID, etc.

Params:
- document_type::String (required)
- process_type::String (required)
- connecting_domain::String (required)
- acquiring_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- type_market_agreement_type::String

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing123_h_i_allocation_and_use_of_cross_zonal_balancing_capacity(_api::BalancingApi, document_type::String, process_type::String, connecting_domain::String, acquiring_domain::String, period_start::Int64, period_end::Int64; type_market_agreement_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing123_h_i_allocation_and_use_of_cross_zonal_balancing_capacity(_api, document_type, process_type, connecting_domain, acquiring_domain, period_start, period_end; type_market_agreement_type=type_market_agreement_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing123_h_i_allocation_and_use_of_cross_zonal_balancing_capacity(_api::BalancingApi, response_stream::Channel, document_type::String, process_type::String, connecting_domain::String, acquiring_domain::String, period_start::Int64, period_end::Int64; type_market_agreement_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing123_h_i_allocation_and_use_of_cross_zonal_balancing_capacity(_api, document_type, process_type, connecting_domain, acquiring_domain, period_start, period_end; type_market_agreement_type=type_market_agreement_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing171_b_c_volumes_and_prices_of_contracted_reserves_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing171_b_c_volumes_and_prices_of_contracted_reserves(_api::BalancingApi, document_type::String, business_type::String, type_market_agreement_type::String, control_area_domain::String, period_start::Int64, period_end::Int64; process_type=nothing, psr_type=nothing, offset=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing171_b_c_volumes_and_prices_of_contracted_reserves_BalancingApi, "/balancing/17-1-b-c-volumes-and-prices-of-contracted-reserves", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Type_MarketAgreement.Type", type_market_agreement_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "controlArea_Domain", control_area_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "psrType", psr_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""17.1.B&C Volumes and Prices of Contracted Reserves

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements in total, counted across all XML documents contained in the ZIP response. The `offset`parameter can be used to retrieve the data in batches of up to 100 TimeSeries, where `offset=0` returns the first 100 elements, `offset=100` returns the next 100, and so on.

Params:
- document_type::String (required)
- business_type::String (required)
- type_market_agreement_type::String (required)
- control_area_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- process_type::String
- psr_type::String
- offset::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing171_b_c_volumes_and_prices_of_contracted_reserves(_api::BalancingApi, document_type::String, business_type::String, type_market_agreement_type::String, control_area_domain::String, period_start::Int64, period_end::Int64; process_type=nothing, psr_type=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing171_b_c_volumes_and_prices_of_contracted_reserves(_api, document_type, business_type, type_market_agreement_type, control_area_domain, period_start, period_end; process_type=process_type, psr_type=psr_type, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing171_b_c_volumes_and_prices_of_contracted_reserves(_api::BalancingApi, response_stream::Channel, document_type::String, business_type::String, type_market_agreement_type::String, control_area_domain::String, period_start::Int64, period_end::Int64; process_type=nothing, psr_type=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing171_b_c_volumes_and_prices_of_contracted_reserves(_api, document_type, business_type, type_market_agreement_type, control_area_domain, period_start, period_end; process_type=process_type, psr_type=psr_type, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing171_f_prices_of_activated_balancing_energy_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing171_f_prices_of_activated_balancing_energy(_api::BalancingApi, document_type::String, process_type::String, control_area_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, export_type=nothing, psr_type=nothing, standard_market_product=nothing, original_market_product=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing171_f_prices_of_activated_balancing_energy_BalancingApi, "/balancing/17-1-f-prices-of-activated-balancing-energy", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "controlArea_Domain", control_area_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "ExportType", export_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "PsrType", psr_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Standard_MarketProduct", standard_market_product; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Original_MarketProduct", original_market_product; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""17.1.F Prices of Activated Balancing Energy

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- process_type::String (required)
- control_area_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- business_type::String
- export_type::String
- psr_type::String
- standard_market_product::String
- original_market_product::String

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing171_f_prices_of_activated_balancing_energy(_api::BalancingApi, document_type::String, process_type::String, control_area_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, export_type=nothing, psr_type=nothing, standard_market_product=nothing, original_market_product=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing171_f_prices_of_activated_balancing_energy(_api, document_type, process_type, control_area_domain, period_start, period_end; business_type=business_type, export_type=export_type, psr_type=psr_type, standard_market_product=standard_market_product, original_market_product=original_market_product, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing171_f_prices_of_activated_balancing_energy(_api::BalancingApi, response_stream::Channel, document_type::String, process_type::String, control_area_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, export_type=nothing, psr_type=nothing, standard_market_product=nothing, original_market_product=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing171_f_prices_of_activated_balancing_energy(_api, document_type, process_type, control_area_domain, period_start, period_end; business_type=business_type, export_type=export_type, psr_type=psr_type, standard_market_product=standard_market_product, original_market_product=original_market_product, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing171_g_imbalance_prices_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing171_g_imbalance_prices(_api::BalancingApi, document_type::String, control_area_domain::String, period_start::Int64, period_end::Int64; psr_type=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing171_g_imbalance_prices_BalancingApi, "/balancing/17-1-g-imbalance-prices", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "controlArea_Domain", control_area_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "PsrType", psr_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""17.1.G Imbalance prices

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- control_area_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- psr_type::String

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing171_g_imbalance_prices(_api::BalancingApi, document_type::String, control_area_domain::String, period_start::Int64, period_end::Int64; psr_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing171_g_imbalance_prices(_api, document_type, control_area_domain, period_start, period_end; psr_type=psr_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing171_g_imbalance_prices(_api::BalancingApi, response_stream::Channel, document_type::String, control_area_domain::String, period_start::Int64, period_end::Int64; psr_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing171_g_imbalance_prices(_api, document_type, control_area_domain, period_start, period_end; psr_type=psr_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing171_h_total_imbalance_volumes_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing171_h_total_imbalance_volumes(_api::BalancingApi, document_type::String, control_area_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing171_h_total_imbalance_volumes_BalancingApi, "/balancing/17-1-h-total-imbalance-volumes", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "controlArea_Domain", control_area_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""17.1.H Total Imbalance Volumes

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- control_area_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- business_type::String

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing171_h_total_imbalance_volumes(_api::BalancingApi, document_type::String, control_area_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing171_h_total_imbalance_volumes(_api, document_type, control_area_domain, period_start, period_end; business_type=business_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing171_h_total_imbalance_volumes(_api::BalancingApi, response_stream::Channel, document_type::String, control_area_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing171_h_total_imbalance_volumes(_api, document_type, control_area_domain, period_start, period_end; business_type=business_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing171_i_financial_expenses_and_income_for_balancing_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing171_i_financial_expenses_and_income_for_balancing(_api::BalancingApi, document_type::String, control_area_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing171_i_financial_expenses_and_income_for_balancing_BalancingApi, "/balancing/17-1-i-financial-expenses-and-income-for-balancing", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "controlArea_Domain", control_area_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""17.1.I Financial Expenses and Income for Balancing

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- control_area_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing171_i_financial_expenses_and_income_for_balancing(_api::BalancingApi, document_type::String, control_area_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_balancing171_i_financial_expenses_and_income_for_balancing(_api, document_type, control_area_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing171_i_financial_expenses_and_income_for_balancing(_api::BalancingApi, response_stream::Channel, document_type::String, control_area_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_balancing171_i_financial_expenses_and_income_for_balancing(_api, document_type, control_area_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing1854_results_of_the_criteria_application_process_measurements_so_gl_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing1854_results_of_the_criteria_application_process_measurements_so_gl(_api::BalancingApi, document_type::String, process_type::String, area_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing1854_results_of_the_criteria_application_process_measurements_so_gl_BalancingApi, "/balancing/185-4-results-of-the-criteria-application-process-measurements-so-gl", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "area_domain", area_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""185.4 Results of the Criteria Application Process - Measurements (SO GL)

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- process_type::String (required)
- area_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing1854_results_of_the_criteria_application_process_measurements_so_gl(_api::BalancingApi, document_type::String, process_type::String, area_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_balancing1854_results_of_the_criteria_application_process_measurements_so_gl(_api, document_type, process_type, area_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing1854_results_of_the_criteria_application_process_measurements_so_gl(_api::BalancingApi, response_stream::Channel, document_type::String, process_type::String, area_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_balancing1854_results_of_the_criteria_application_process_measurements_so_gl(_api, document_type, process_type, area_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing1872_fcr_total_capacity_so_gl_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing1872_fcr_total_capacity_so_gl(_api::BalancingApi; document_type=nothing, business_type=nothing, area_domain=nothing, period_start=nothing, period_end=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing1872_fcr_total_capacity_so_gl_BalancingApi, "/balancing/187-2-fcr-total-capacity-so-gl", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "area_Domain", area_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""187.2 FCR Total capacity (SO GL)

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String
- business_type::String
- area_domain::String
- period_start::Int64
- period_end::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing1872_fcr_total_capacity_so_gl(_api::BalancingApi; document_type=nothing, business_type=nothing, area_domain=nothing, period_start=nothing, period_end=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing1872_fcr_total_capacity_so_gl(_api; document_type=document_type, business_type=business_type, area_domain=area_domain, period_start=period_start, period_end=period_end, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing1872_fcr_total_capacity_so_gl(_api::BalancingApi, response_stream::Channel; document_type=nothing, business_type=nothing, area_domain=nothing, period_start=nothing, period_end=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing1872_fcr_total_capacity_so_gl(_api; document_type=document_type, business_type=business_type, area_domain=area_domain, period_start=period_start, period_end=period_end, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing1872_shares_of_fcr_capacity_so_gl_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing1872_shares_of_fcr_capacity_so_gl(_api::BalancingApi; document_type=nothing, business_type=nothing, area_domain=nothing, period_start=nothing, period_end=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing1872_shares_of_fcr_capacity_so_gl_BalancingApi, "/balancing/187-2-shares-of-fcr-capacity-so-gl", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "area_Domain", area_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""187.2 Shares of FCR capacity (SO GL)

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String
- business_type::String
- area_domain::String
- period_start::Int64
- period_end::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing1872_shares_of_fcr_capacity_so_gl(_api::BalancingApi; document_type=nothing, business_type=nothing, area_domain=nothing, period_start=nothing, period_end=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing1872_shares_of_fcr_capacity_so_gl(_api; document_type=document_type, business_type=business_type, area_domain=area_domain, period_start=period_start, period_end=period_end, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing1872_shares_of_fcr_capacity_so_gl(_api::BalancingApi, response_stream::Channel; document_type=nothing, business_type=nothing, area_domain=nothing, period_start=nothing, period_end=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing1872_shares_of_fcr_capacity_so_gl(_api; document_type=document_type, business_type=business_type, area_domain=area_domain, period_start=period_start, period_end=period_end, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing18831892_frr_rr_capacity_outlook_so_gl_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing18831892_frr_rr_capacity_outlook_so_gl(_api::BalancingApi, document_type::String, process_type::String, business_type::String, area_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing18831892_frr_rr_capacity_outlook_so_gl_BalancingApi, "/balancing/188-3-189-2-frr-rr-capacity-outlook-so-gl", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "area_Domain", area_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""188.3 & 189.2 FRR & RR Capacity Outlook (SO GL)

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- process_type::String (required)
- business_type::String (required)
- area_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing18831892_frr_rr_capacity_outlook_so_gl(_api::BalancingApi, document_type::String, process_type::String, business_type::String, area_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_balancing18831892_frr_rr_capacity_outlook_so_gl(_api, document_type, process_type, business_type, area_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing18831892_frr_rr_capacity_outlook_so_gl(_api::BalancingApi, response_stream::Channel, document_type::String, process_type::String, business_type::String, area_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_balancing18831892_frr_rr_capacity_outlook_so_gl(_api, document_type, process_type, business_type, area_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing18841893_frr_and_rr_actual_capacity_so_gl_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing18841893_frr_and_rr_actual_capacity_so_gl(_api::BalancingApi, document_type::String, process_type::String, business_type::String, area_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing18841893_frr_and_rr_actual_capacity_so_gl_BalancingApi, "/balancing/188-4-189-3-frr-and-rr-actual-capacity-so-gl", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "area_Domain", area_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""188.4 & 189.3 FRR and RR Actual Capacity (SO GL)

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- process_type::String (required)
- business_type::String (required)
- area_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing18841893_frr_and_rr_actual_capacity_so_gl(_api::BalancingApi, document_type::String, process_type::String, business_type::String, area_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_balancing18841893_frr_and_rr_actual_capacity_so_gl(_api, document_type, process_type, business_type, area_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing18841893_frr_and_rr_actual_capacity_so_gl(_api::BalancingApi, response_stream::Channel, document_type::String, process_type::String, business_type::String, area_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_balancing18841893_frr_and_rr_actual_capacity_so_gl(_api, document_type, process_type, business_type, area_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing1892_outlook_of_reserve_capacities_on_rr_so_gl_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing1892_outlook_of_reserve_capacities_on_rr_so_gl(_api::BalancingApi; document_type=nothing, process_type=nothing, business_type=nothing, area_domain=nothing, period_start=nothing, period_end=nothing, offset=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing1892_outlook_of_reserve_capacities_on_rr_so_gl_BalancingApi, "/balancing/189-2-outlook-of-reserve-capacities-on-rr-so-gl", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "area_Domain", area_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""189.2 Outlook of Reserve Capacities on RR (SO GL)

Params:
- document_type::String
- process_type::String
- business_type::String
- area_domain::String
- period_start::Int64
- period_end::Int64
- offset::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing1892_outlook_of_reserve_capacities_on_rr_so_gl(_api::BalancingApi; document_type=nothing, process_type=nothing, business_type=nothing, area_domain=nothing, period_start=nothing, period_end=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing1892_outlook_of_reserve_capacities_on_rr_so_gl(_api; document_type=document_type, process_type=process_type, business_type=business_type, area_domain=area_domain, period_start=period_start, period_end=period_end, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing1892_outlook_of_reserve_capacities_on_rr_so_gl(_api::BalancingApi, response_stream::Channel; document_type=nothing, process_type=nothing, business_type=nothing, area_domain=nothing, period_start=nothing, period_end=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing1892_outlook_of_reserve_capacities_on_rr_so_gl(_api; document_type=document_type, process_type=process_type, business_type=business_type, area_domain=area_domain, period_start=period_start, period_end=period_end, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing1893_rr_actual_capacity_so_gl_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing1893_rr_actual_capacity_so_gl(_api::BalancingApi; document_type=nothing, process_type=nothing, business_type=nothing, area_domain=nothing, period_start=nothing, period_end=nothing, offset=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing1893_rr_actual_capacity_so_gl_BalancingApi, "/balancing/189-3-rr-actual-capacity-so-gl", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "area_Domain", area_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""189.3 RR Actual Capacity(SO GL)

Params:
- document_type::String
- process_type::String
- business_type::String
- area_domain::String
- period_start::Int64
- period_end::Int64
- offset::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing1893_rr_actual_capacity_so_gl(_api::BalancingApi; document_type=nothing, process_type=nothing, business_type=nothing, area_domain=nothing, period_start=nothing, period_end=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing1893_rr_actual_capacity_so_gl(_api; document_type=document_type, process_type=process_type, business_type=business_type, area_domain=area_domain, period_start=period_start, period_end=period_end, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing1893_rr_actual_capacity_so_gl(_api::BalancingApi, response_stream::Channel; document_type=nothing, process_type=nothing, business_type=nothing, area_domain=nothing, period_start=nothing, period_end=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing1893_rr_actual_capacity_so_gl(_api; document_type=document_type, process_type=process_type, business_type=business_type, area_domain=area_domain, period_start=period_start, period_end=period_end, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing1901_sharing_of_rr_and_frr_so_gl_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing1901_sharing_of_rr_and_frr_so_gl(_api::BalancingApi; document_type=nothing, process_type=nothing, business_type=nothing, acquiring_domain=nothing, connecting_domain=nothing, period_start=nothing, period_end=nothing, offset=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing1901_sharing_of_rr_and_frr_so_gl_BalancingApi, "/balancing/190-1-sharing-of-rr-and-frr-so-gl", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "BusinessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Acquiring_Domain", acquiring_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Connecting_Domain", connecting_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""190.1 Sharing of RR and FRR (SO GL)

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements is returned per XML response. The `offset`parameter can be used to retrieve the data in batches of up to 100 TimeSeries, where `offset=0` returns the first 100 elements, `offset=100` returns the next 100, and so on.

Params:
- document_type::String
- process_type::String
- business_type::String
- acquiring_domain::String
- connecting_domain::String
- period_start::Int64
- period_end::Int64
- offset::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing1901_sharing_of_rr_and_frr_so_gl(_api::BalancingApi; document_type=nothing, process_type=nothing, business_type=nothing, acquiring_domain=nothing, connecting_domain=nothing, period_start=nothing, period_end=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing1901_sharing_of_rr_and_frr_so_gl(_api; document_type=document_type, process_type=process_type, business_type=business_type, acquiring_domain=acquiring_domain, connecting_domain=connecting_domain, period_start=period_start, period_end=period_end, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing1901_sharing_of_rr_and_frr_so_gl(_api::BalancingApi, response_stream::Channel; document_type=nothing, process_type=nothing, business_type=nothing, acquiring_domain=nothing, connecting_domain=nothing, period_start=nothing, period_end=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing1901_sharing_of_rr_and_frr_so_gl(_api; document_type=document_type, process_type=process_type, business_type=business_type, acquiring_domain=acquiring_domain, connecting_domain=connecting_domain, period_start=period_start, period_end=period_end, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing1902_sharing_of_fcr_between_sas_so_gl_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing1902_sharing_of_fcr_between_sas_so_gl(_api::BalancingApi; document_type=nothing, process_type=nothing, business_type=nothing, area_domain=nothing, period_start=nothing, period_end=nothing, offset=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing1902_sharing_of_fcr_between_sas_so_gl_BalancingApi, "/balancing/190-2-sharing-of-fcr-between-sas-so-gl", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "area_Domain", area_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""190.2 Sharing of FCR between SAs (SO GL)

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements is returned per XML response. The `offset`parameter can be used to retrieve the data in batches of up to 100 TimeSeries, where `offset=0` returns the first 100 elements, `offset=100` returns the next 100, and so on.

Params:
- document_type::String
- process_type::String
- business_type::String
- area_domain::String
- period_start::Int64
- period_end::Int64
- offset::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing1902_sharing_of_fcr_between_sas_so_gl(_api::BalancingApi; document_type=nothing, process_type=nothing, business_type=nothing, area_domain=nothing, period_start=nothing, period_end=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing1902_sharing_of_fcr_between_sas_so_gl(_api; document_type=document_type, process_type=process_type, business_type=business_type, area_domain=area_domain, period_start=period_start, period_end=period_end, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing1902_sharing_of_fcr_between_sas_so_gl(_api::BalancingApi, response_stream::Channel; document_type=nothing, process_type=nothing, business_type=nothing, area_domain=nothing, period_start=nothing, period_end=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing1902_sharing_of_fcr_between_sas_so_gl(_api; document_type=document_type, process_type=process_type, business_type=business_type, area_domain=area_domain, period_start=period_start, period_end=period_end, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing1903_exchanged_reserve_capacity_so_gl_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing1903_exchanged_reserve_capacity_so_gl(_api::BalancingApi; document_type=nothing, process_type=nothing, business_type=nothing, acquiring_domain=nothing, connecting_domain=nothing, period_start=nothing, period_end=nothing, offset=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing1903_exchanged_reserve_capacity_so_gl_BalancingApi, "/balancing/190-3-exchanged-reserve-capacity-so-gl", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "BusinessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Acquiring_Domain", acquiring_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Connecting_Domain", connecting_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""190.3 Exchanged Reserve Capacity (SO GL)

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements in total, counted across all XML documents contained in the ZIP response. The `offset`parameter can be used to retrieve the data in batches of up to 100 TimeSeries, where `offset=0` returns the first 100 elements, `offset=100` returns the next 100, and so on.

Params:
- document_type::String
- process_type::String
- business_type::String
- acquiring_domain::String
- connecting_domain::String
- period_start::Int64
- period_end::Int64
- offset::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing1903_exchanged_reserve_capacity_so_gl(_api::BalancingApi; document_type=nothing, process_type=nothing, business_type=nothing, acquiring_domain=nothing, connecting_domain=nothing, period_start=nothing, period_end=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing1903_exchanged_reserve_capacity_so_gl(_api; document_type=document_type, process_type=process_type, business_type=business_type, acquiring_domain=acquiring_domain, connecting_domain=connecting_domain, period_start=period_start, period_end=period_end, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing1903_exchanged_reserve_capacity_so_gl(_api::BalancingApi, response_stream::Channel; document_type=nothing, process_type=nothing, business_type=nothing, acquiring_domain=nothing, connecting_domain=nothing, period_start=nothing, period_end=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing1903_exchanged_reserve_capacity_so_gl(_api; document_type=document_type, process_type=process_type, business_type=business_type, acquiring_domain=acquiring_domain, connecting_domain=connecting_domain, period_start=period_start, period_end=period_end, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing_if_afrr316_cross_border_marginal_prices_cbmps_for_afrr_central_selection_cs_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing_if_afrr316_cross_border_marginal_prices_cbmps_for_afrr_central_selection_cs(_api::BalancingApi, document_type::String, process_type::String, business_type::String, standard_market_product::String, control_area_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing_if_afrr316_cross_border_marginal_prices_cbmps_for_afrr_central_selection_cs_BalancingApi, "/balancing/if-afrr-3-16-cross-border-marginal-prices-cbmps-for-afrr-central-selection-cs", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Standard_MarketProduct", standard_market_product; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "controlArea_Domain", control_area_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""IF aFRR 3.16 Cross Border Marginal Prices (CBMPs) for aFRR Central Selection (CS)

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 day.

Params:
- document_type::String (required)
- process_type::String (required)
- business_type::String (required)
- standard_market_product::String (required)
- control_area_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing_if_afrr316_cross_border_marginal_prices_cbmps_for_afrr_central_selection_cs(_api::BalancingApi, document_type::String, process_type::String, business_type::String, standard_market_product::String, control_area_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_balancing_if_afrr316_cross_border_marginal_prices_cbmps_for_afrr_central_selection_cs(_api, document_type, process_type, business_type, standard_market_product, control_area_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing_if_afrr316_cross_border_marginal_prices_cbmps_for_afrr_central_selection_cs(_api::BalancingApi, response_stream::Channel, document_type::String, process_type::String, business_type::String, standard_market_product::String, control_area_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_balancing_if_afrr316_cross_border_marginal_prices_cbmps_for_afrr_central_selection_cs(_api, document_type, process_type, business_type, standard_market_product, control_area_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing_ifs310316317_netted_and_exchanged_volumes_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing_ifs310316317_netted_and_exchanged_volumes(_api::BalancingApi, document_type::String, process_type::String, acquiring_domain::String, connecting_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing_ifs310316317_netted_and_exchanged_volumes_BalancingApi, "/balancing/ifs-3-10-3-16-3-17-netted-and-exchanged-volumes", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Acquiring_Domain", acquiring_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Connecting_Domain", connecting_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""IFs 3.10, 3.16 & 3.17 Netted and Exchanged Volumes

<u><b>Request limit:</b></u>  - For aFRR: Each request may cover a period of up to 1 day.      - For other process types: Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- process_type::String (required)
- acquiring_domain::String (required)
- connecting_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing_ifs310316317_netted_and_exchanged_volumes(_api::BalancingApi, document_type::String, process_type::String, acquiring_domain::String, connecting_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_balancing_ifs310316317_netted_and_exchanged_volumes(_api, document_type, process_type, acquiring_domain, connecting_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing_ifs310316317_netted_and_exchanged_volumes(_api::BalancingApi, response_stream::Channel, document_type::String, process_type::String, acquiring_domain::String, connecting_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_balancing_ifs310316317_netted_and_exchanged_volumes(_api, document_type, process_type, acquiring_domain, connecting_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing_ifs310316317_netted_and_exchanged_volumes_per_border_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing_ifs310316317_netted_and_exchanged_volumes_per_border(_api::BalancingApi, document_type::String, process_type::String, acquiring_domain::String, connecting_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing_ifs310316317_netted_and_exchanged_volumes_per_border_BalancingApi, "/balancing/ifs-3-10-3-16-3-17-netted-and-exchanged-volumes-per-border", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Acquiring_Domain", acquiring_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Connecting_Domain", connecting_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""IFs 3.10, 3.16 & 3.17 Netted and Exchanged Volumes per Border

<u><b>Request limit:</b></u>  - For aFRR: Each request may cover a period of up to 1 day.      - For other process types: Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- process_type::String (required)
- acquiring_domain::String (required)
- connecting_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing_ifs310316317_netted_and_exchanged_volumes_per_border(_api::BalancingApi, document_type::String, process_type::String, acquiring_domain::String, connecting_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_balancing_ifs310316317_netted_and_exchanged_volumes_per_border(_api, document_type, process_type, acquiring_domain, connecting_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing_ifs310316317_netted_and_exchanged_volumes_per_border(_api::BalancingApi, response_stream::Channel, document_type::String, process_type::String, acquiring_domain::String, connecting_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_balancing_ifs310316317_netted_and_exchanged_volumes_per_border(_api, document_type, process_type, acquiring_domain, connecting_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing_ifs4344_balancing_border_capacity_limitations_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing_ifs4344_balancing_border_capacity_limitations(_api::BalancingApi, document_type::String, business_type::String, process_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; registered_resource=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing_ifs4344_balancing_border_capacity_limitations_BalancingApi, "/balancing/ifs-4-3-4-4-balancing-border-capacity-limitations", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "BusinessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "In_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "registeredResource", registered_resource; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""IFs 4.3 & 4.4 Balancing Border Capacity Limitations

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- business_type::String (required)
- process_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- registered_resource::String

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing_ifs4344_balancing_border_capacity_limitations(_api::BalancingApi, document_type::String, business_type::String, process_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; registered_resource=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing_ifs4344_balancing_border_capacity_limitations(_api, document_type, business_type, process_type, out_domain, in_domain, period_start, period_end; registered_resource=registered_resource, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing_ifs4344_balancing_border_capacity_limitations(_api::BalancingApi, response_stream::Channel, document_type::String, business_type::String, process_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; registered_resource=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing_ifs4344_balancing_border_capacity_limitations(_api, document_type, business_type, process_type, out_domain, in_domain, period_start, period_end; registered_resource=registered_resource, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing_ifs45_permanent_allocation_limitations_to_cross_border_capacity_on_hvdc_lines_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing_ifs45_permanent_allocation_limitations_to_cross_border_capacity_on_hvdc_lines(_api::BalancingApi, document_type::String, process_type::String, business_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; registered_resource=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing_ifs45_permanent_allocation_limitations_to_cross_border_capacity_on_hvdc_lines_BalancingApi, "/balancing/ifs-4-5-permanent-allocation-limitations-to-cross-border-capacity-on-hvdc-lines", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "BusinessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "In_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "registeredResource", registered_resource; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""IFs 4.5 Permanent Allocation Limitations to Cross-border Capacity on HVDC Lines

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements is returned per XML response.

Params:
- document_type::String (required)
- process_type::String (required)
- business_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- registered_resource::String

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing_ifs45_permanent_allocation_limitations_to_cross_border_capacity_on_hvdc_lines(_api::BalancingApi, document_type::String, process_type::String, business_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; registered_resource=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing_ifs45_permanent_allocation_limitations_to_cross_border_capacity_on_hvdc_lines(_api, document_type, process_type, business_type, out_domain, in_domain, period_start, period_end; registered_resource=registered_resource, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing_ifs45_permanent_allocation_limitations_to_cross_border_capacity_on_hvdc_lines(_api::BalancingApi, response_stream::Channel, document_type::String, process_type::String, business_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; registered_resource=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing_ifs45_permanent_allocation_limitations_to_cross_border_capacity_on_hvdc_lines(_api, document_type, process_type, business_type, out_domain, in_domain, period_start, period_end; registered_resource=registered_resource, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing_ifs_afrr34_mfrr34_elastic_demands_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing_ifs_afrr34_mfrr34_elastic_demands(_api::BalancingApi, document_type::String, business_type::String, process_type::String, acquiring_domain::String, period_start::Int64, period_end::Int64; offset=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing_ifs_afrr34_mfrr34_elastic_demands_BalancingApi, "/balancing/ifs-afrr-3-4-mfrr-3-4-elastic-demands", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Acquiring_Domain", acquiring_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""IFs aFRR 3.4 & mFRR 3.4 Elastic Demands

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements is returned per XML response. The `offset`parameter can be used to retrieve the data in batches of up to 100 TimeSeries, where `offset=0` returns the first 100 elements, `offset=100` returns the next 100, and so on.

Params:
- document_type::String (required)
- business_type::String (required)
- process_type::String (required)
- acquiring_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- offset::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing_ifs_afrr34_mfrr34_elastic_demands(_api::BalancingApi, document_type::String, business_type::String, process_type::String, acquiring_domain::String, period_start::Int64, period_end::Int64; offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing_ifs_afrr34_mfrr34_elastic_demands(_api, document_type, business_type, process_type, acquiring_domain, period_start, period_end; offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing_ifs_afrr34_mfrr34_elastic_demands(_api::BalancingApi, response_stream::Channel, document_type::String, business_type::String, process_type::String, acquiring_domain::String, period_start::Int64, period_end::Int64; offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing_ifs_afrr34_mfrr34_elastic_demands(_api, document_type, business_type, process_type, acquiring_domain, period_start, period_end; offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing_ifs_mfrr99_afrr9698_changes_to_bid_availability_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing_ifs_mfrr99_afrr9698_changes_to_bid_availability(_api::BalancingApi, document_type::String, process_type::String, domain::String, period_start::Int64, period_end::Int64; business_type=nothing, offset=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing_ifs_mfrr99_afrr9698_changes_to_bid_availability_BalancingApi, "/balancing/ifs-mfrr-9-9-afrr-9-6-9-8-changes-to-bid-availability", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Domain", domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""IFs mFRR 9.9, aFRR 9.6&9.8 Changes to Bid Availability

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements is returned per XML response. The `offset`parameter can be used to retrieve the data in batches of up to 100 TimeSeries, where `offset=0` returns the first 100 elements, `offset=100` returns the next 100, and so on.

Params:
- document_type::String (required)
- process_type::String (required)
- domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- business_type::String
- offset::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing_ifs_mfrr99_afrr9698_changes_to_bid_availability(_api::BalancingApi, document_type::String, process_type::String, domain::String, period_start::Int64, period_end::Int64; business_type=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing_ifs_mfrr99_afrr9698_changes_to_bid_availability(_api, document_type, process_type, domain, period_start, period_end; business_type=business_type, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing_ifs_mfrr99_afrr9698_changes_to_bid_availability(_api::BalancingApi, response_stream::Channel, document_type::String, process_type::String, domain::String, period_start::Int64, period_end::Int64; business_type=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing_ifs_mfrr99_afrr9698_changes_to_bid_availability(_api, document_type, process_type, domain, period_start, period_end; business_type=business_type, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_balancing_ifs_mfrr99_afrr9698_changes_to_bid_availability_archives_BalancingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_balancing_ifs_mfrr99_afrr9698_changes_to_bid_availability_archives(_api::BalancingApi, document_type::String, process_type::String, domain::String, period_start::Int64, period_end::Int64, storage_type::String; business_type=nothing, offset=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_balancing_ifs_mfrr99_afrr9698_changes_to_bid_availability_archives_BalancingApi, "/balancing/ifs-mfrr-9-9-afrr-9-6-9-8-changes-to-bid-availability-archives", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Domain", domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "storageType", storage_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""IFs mFRR 9.9, aFRR 9.6&9.8 Changes to Bid Availability Archives

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 ZIP files contained in the ZIP response. The `offset`parameter can be used to retrieve the data in batches of up to 100 ZIP archives, where`offset=0` returns the first 100 archives, `offset=100` returns the next 100, and so on.

Params:
- document_type::String (required)
- process_type::String (required)
- domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- storage_type::String (required)
- business_type::String
- offset::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function balancing_ifs_mfrr99_afrr9698_changes_to_bid_availability_archives(_api::BalancingApi, document_type::String, process_type::String, domain::String, period_start::Int64, period_end::Int64, storage_type::String; business_type=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing_ifs_mfrr99_afrr9698_changes_to_bid_availability_archives(_api, document_type, process_type, domain, period_start, period_end, storage_type; business_type=business_type, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function balancing_ifs_mfrr99_afrr9698_changes_to_bid_availability_archives(_api::BalancingApi, response_stream::Channel, document_type::String, process_type::String, domain::String, period_start::Int64, period_end::Int64, storage_type::String; business_type=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_balancing_ifs_mfrr99_afrr9698_changes_to_bid_availability_archives(_api, document_type, process_type, domain, period_start, period_end, storage_type; business_type=business_type, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export balancing123_a_current_balancing_state_gl_eb
export balancing123_b_c_balancing_energy_bids
export balancing123_b_c_balancing_energy_bids_archives
export balancing123_e_aggregated_balancing_energy_bids_gl_eb
export balancing123_f_procured_balancing_capacity_gl_eb
export balancing123_h_i_allocation_and_use_of_cross_zonal_balancing_capacity
export balancing171_b_c_volumes_and_prices_of_contracted_reserves
export balancing171_f_prices_of_activated_balancing_energy
export balancing171_g_imbalance_prices
export balancing171_h_total_imbalance_volumes
export balancing171_i_financial_expenses_and_income_for_balancing
export balancing1854_results_of_the_criteria_application_process_measurements_so_gl
export balancing1872_fcr_total_capacity_so_gl
export balancing1872_shares_of_fcr_capacity_so_gl
export balancing18831892_frr_rr_capacity_outlook_so_gl
export balancing18841893_frr_and_rr_actual_capacity_so_gl
export balancing1892_outlook_of_reserve_capacities_on_rr_so_gl
export balancing1893_rr_actual_capacity_so_gl
export balancing1901_sharing_of_rr_and_frr_so_gl
export balancing1902_sharing_of_fcr_between_sas_so_gl
export balancing1903_exchanged_reserve_capacity_so_gl
export balancing_if_afrr316_cross_border_marginal_prices_cbmps_for_afrr_central_selection_cs
export balancing_ifs310316317_netted_and_exchanged_volumes
export balancing_ifs310316317_netted_and_exchanged_volumes_per_border
export balancing_ifs4344_balancing_border_capacity_limitations
export balancing_ifs45_permanent_allocation_limitations_to_cross_border_capacity_on_hvdc_lines
export balancing_ifs_afrr34_mfrr34_elastic_demands
export balancing_ifs_mfrr99_afrr9698_changes_to_bid_availability
export balancing_ifs_mfrr99_afrr9698_changes_to_bid_availability_archives
