# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct OMIApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `OMIApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ OMIApi }) = "https://web-api.tp.entsoe.eu/api"

const _returntypes_omi_other_market_information_OMIApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_omi_other_market_information(_api::OMIApi, document_type::String, control_area_domain::String, period_start::Int64, period_end::Int64; doc_status=nothing, period_start_update=nothing, period_end_update=nothing, offset=nothing, m_r_i_d=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_omi_other_market_information_OMIApi, "/omi/other-market-information", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "ControlArea_Domain", control_area_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "DocStatus", doc_status; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "PeriodStartUpdate", period_start_update; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "PeriodEndUpdate", period_end_update; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "mRID", m_r_i_d; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Other Market Information

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.  - It applies to PeriodStart and PeriodEnd if PeriodStartUpdate and PeriodEndUpdate parameters are not included in the request.      - It applies only to PeriodStartUpdate and PeriodEndUpdate if included in the request.       <u><b>Response limit</b></u>: A maximum of 200 XML documents contained in the ZIP response. The `offset`parameter can be used to retrieve the data in batches of up to 200 XML documents, where `offset=0` returns the first 200 documents, `offset=200` returns the next 200, and so on.

Params:
- document_type::String (required)
- control_area_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- doc_status::String
- period_start_update::Int64
- period_end_update::Int64
- offset::Int64
- m_r_i_d::String

Return: String, OpenAPI.Clients.ApiResponse
"""
function omi_other_market_information(_api::OMIApi, document_type::String, control_area_domain::String, period_start::Int64, period_end::Int64; doc_status=nothing, period_start_update=nothing, period_end_update=nothing, offset=nothing, m_r_i_d=nothing, _mediaType=nothing)
    _ctx = _oacinternal_omi_other_market_information(_api, document_type, control_area_domain, period_start, period_end; doc_status=doc_status, period_start_update=period_start_update, period_end_update=period_end_update, offset=offset, m_r_i_d=m_r_i_d, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function omi_other_market_information(_api::OMIApi, response_stream::Channel, document_type::String, control_area_domain::String, period_start::Int64, period_end::Int64; doc_status=nothing, period_start_update=nothing, period_end_update=nothing, offset=nothing, m_r_i_d=nothing, _mediaType=nothing)
    _ctx = _oacinternal_omi_other_market_information(_api, document_type, control_area_domain, period_start, period_end; doc_status=doc_status, period_start_update=period_start_update, period_end_update=period_end_update, offset=offset, m_r_i_d=m_r_i_d, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export omi_other_market_information
