# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct MarketApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `MarketApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ MarketApi }) = "https://web-api.tp.entsoe.eu/api"

const _returntypes_market111_a_explicit_allocations_offered_transfer_capacity_MarketApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_market111_a_explicit_allocations_offered_transfer_capacity(_api::MarketApi, document_type::String, auction_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; auction_category=nothing, update_date_and_or_time=nothing, classification_sequence_attribute_instance_component_position=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_market111_a_explicit_allocations_offered_transfer_capacity_MarketApi, "/market/11-1-a-explicit-allocations-offered-transfer-capacity", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "auction.Type", auction_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "contract_MarketAgreement.Type", contract_market_agreement_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "auction.Category", auction_category; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Update_DateAndOrTime", update_date_and_or_time; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "ClassificationSequence_AttributeInstanceComponent.Position", classification_sequence_attribute_instance_component_position; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""11.1.A Explicit Allocations - Offered Transfer Capacity

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements is returned per XML response.

Params:
- document_type::String (required)
- auction_type::String (required)
- contract_market_agreement_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- auction_category::String
- update_date_and_or_time::Int64
- classification_sequence_attribute_instance_component_position::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function market111_a_explicit_allocations_offered_transfer_capacity(_api::MarketApi, document_type::String, auction_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; auction_category=nothing, update_date_and_or_time=nothing, classification_sequence_attribute_instance_component_position=nothing, _mediaType=nothing)
    _ctx = _oacinternal_market111_a_explicit_allocations_offered_transfer_capacity(_api, document_type, auction_type, contract_market_agreement_type, out_domain, in_domain, period_start, period_end; auction_category=auction_category, update_date_and_or_time=update_date_and_or_time, classification_sequence_attribute_instance_component_position=classification_sequence_attribute_instance_component_position, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function market111_a_explicit_allocations_offered_transfer_capacity(_api::MarketApi, response_stream::Channel, document_type::String, auction_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; auction_category=nothing, update_date_and_or_time=nothing, classification_sequence_attribute_instance_component_position=nothing, _mediaType=nothing)
    _ctx = _oacinternal_market111_a_explicit_allocations_offered_transfer_capacity(_api, document_type, auction_type, contract_market_agreement_type, out_domain, in_domain, period_start, period_end; auction_category=auction_category, update_date_and_or_time=update_date_and_or_time, classification_sequence_attribute_instance_component_position=classification_sequence_attribute_instance_component_position, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_market111_b_flow_based_allocations_MarketApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_market111_b_flow_based_allocations(_api::MarketApi, document_type::String, process_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_market111_b_flow_based_allocations_MarketApi, "/market/11-1-b-flow-based-allocations", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""11.1.B Flow Based Allocations

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 1 instances contained in the ZIP response, split into several files within the response ZIP file.

Params:
- document_type::String (required)
- process_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function market111_b_flow_based_allocations(_api::MarketApi, document_type::String, process_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_market111_b_flow_based_allocations(_api, document_type, process_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function market111_b_flow_based_allocations(_api::MarketApi, response_stream::Channel, document_type::String, process_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_market111_b_flow_based_allocations(_api, document_type, process_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_market111_b_flow_based_allocations_archives_MarketApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_market111_b_flow_based_allocations_archives(_api::MarketApi, document_type::String, process_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64, storage_type::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_market111_b_flow_based_allocations_archives_MarketApi, "/market/11-1-b-flow-based-allocations-archives", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "processType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "StorageType", storage_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""11.1.B Flow Based Allocations Archives

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 1 archive in the ZIP response.

Params:
- document_type::String (required)
- process_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- storage_type::String (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function market111_b_flow_based_allocations_archives(_api::MarketApi, document_type::String, process_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64, storage_type::String; _mediaType=nothing)
    _ctx = _oacinternal_market111_b_flow_based_allocations_archives(_api, document_type, process_type, out_domain, in_domain, period_start, period_end, storage_type; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function market111_b_flow_based_allocations_archives(_api::MarketApi, response_stream::Channel, document_type::String, process_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64, storage_type::String; _mediaType=nothing)
    _ctx = _oacinternal_market111_b_flow_based_allocations_archives(_api, document_type, process_type, out_domain, in_domain, period_start, period_end, storage_type; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_market111_continuous_allocations_offered_transfer_capacity_MarketApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_market111_continuous_allocations_offered_transfer_capacity(_api::MarketApi, document_type::String, auction_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64, contract_market_agreement_type::String; update_date_and_or_time=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_market111_continuous_allocations_offered_transfer_capacity_MarketApi, "/market/11-1-continuous-allocations-offered-transfer-capacity", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "DocumentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Auction.Type", auction_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "In_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "PeriodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "PeriodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Contract_MarketAgreement.Type", contract_market_agreement_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Update_DateAndOrTime", update_date_and_or_time; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""11.1 Continuous Allocations - Offered Transfer Capacity

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements is returned per XML response. The `offset`parameter can be used to retrieve the data in batches of up to 100 TimeSeries, where `offset=0` returns the first 100 elements, `offset=100` returns the next 100, and so on.

Params:
- document_type::String (required)
- auction_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- contract_market_agreement_type::String (required)
- update_date_and_or_time::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function market111_continuous_allocations_offered_transfer_capacity(_api::MarketApi, document_type::String, auction_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64, contract_market_agreement_type::String; update_date_and_or_time=nothing, _mediaType=nothing)
    _ctx = _oacinternal_market111_continuous_allocations_offered_transfer_capacity(_api, document_type, auction_type, out_domain, in_domain, period_start, period_end, contract_market_agreement_type; update_date_and_or_time=update_date_and_or_time, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function market111_continuous_allocations_offered_transfer_capacity(_api::MarketApi, response_stream::Channel, document_type::String, auction_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64, contract_market_agreement_type::String; update_date_and_or_time=nothing, _mediaType=nothing)
    _ctx = _oacinternal_market111_continuous_allocations_offered_transfer_capacity(_api, document_type, auction_type, out_domain, in_domain, period_start, period_end, contract_market_agreement_type; update_date_and_or_time=update_date_and_or_time, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_market111_implicit_allocations_offered_transfer_capacity_MarketApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_market111_implicit_allocations_offered_transfer_capacity(_api::MarketApi, document_type::String, auction_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; update_date_and_or_time=nothing, classification_sequence_attribute_instance_component_position=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_market111_implicit_allocations_offered_transfer_capacity_MarketApi, "/market/11-1-implicit-allocations-offered-transfer-capacity", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "auction.Type", auction_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "contract_MarketAgreement.Type", contract_market_agreement_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Update_DateAndOrTime", update_date_and_or_time; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "ClassificationSequence_AttributeInstanceComponent.Position", classification_sequence_attribute_instance_component_position; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""11.1 Implicit Allocations - Offered Transfer Capacity

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements is returned per XML response.

Params:
- document_type::String (required)
- auction_type::String (required)
- contract_market_agreement_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- update_date_and_or_time::Int64
- classification_sequence_attribute_instance_component_position::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function market111_implicit_allocations_offered_transfer_capacity(_api::MarketApi, document_type::String, auction_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; update_date_and_or_time=nothing, classification_sequence_attribute_instance_component_position=nothing, _mediaType=nothing)
    _ctx = _oacinternal_market111_implicit_allocations_offered_transfer_capacity(_api, document_type, auction_type, contract_market_agreement_type, out_domain, in_domain, period_start, period_end; update_date_and_or_time=update_date_and_or_time, classification_sequence_attribute_instance_component_position=classification_sequence_attribute_instance_component_position, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function market111_implicit_allocations_offered_transfer_capacity(_api::MarketApi, response_stream::Channel, document_type::String, auction_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; update_date_and_or_time=nothing, classification_sequence_attribute_instance_component_position=nothing, _mediaType=nothing)
    _ctx = _oacinternal_market111_implicit_allocations_offered_transfer_capacity(_api, document_type, auction_type, contract_market_agreement_type, out_domain, in_domain, period_start, period_end; update_date_and_or_time=update_date_and_or_time, classification_sequence_attribute_instance_component_position=classification_sequence_attribute_instance_component_position, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_market121_a_explicit_allocations_auction_revenue_MarketApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_market121_a_explicit_allocations_auction_revenue(_api::MarketApi, document_type::String, business_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_market121_a_explicit_allocations_auction_revenue_MarketApi, "/market/12-1-a-explicit-allocations-auction-revenue", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "contract_MarketAgreement.Type", contract_market_agreement_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""12.1.A Explicit Allocations - Auction Revenue

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements is returned per XML response.

Params:
- document_type::String (required)
- business_type::String (required)
- contract_market_agreement_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function market121_a_explicit_allocations_auction_revenue(_api::MarketApi, document_type::String, business_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_market121_a_explicit_allocations_auction_revenue(_api, document_type, business_type, contract_market_agreement_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function market121_a_explicit_allocations_auction_revenue(_api::MarketApi, response_stream::Channel, document_type::String, business_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_market121_a_explicit_allocations_auction_revenue(_api, document_type, business_type, contract_market_agreement_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_market121_a_explicit_allocations_use_of_the_transfer_capacity_MarketApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_market121_a_explicit_allocations_use_of_the_transfer_capacity(_api::MarketApi, document_type::String, business_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; auction_category=nothing, classification_sequence_attribute_instance_component_position=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_market121_a_explicit_allocations_use_of_the_transfer_capacity_MarketApi, "/market/12-1-a-explicit-allocations-use-of-the-transfer-capacity", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "contract_MarketAgreement.Type", contract_market_agreement_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Auction.Category", auction_category; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "ClassificationSequence_AttributeInstanceComponent.Position", classification_sequence_attribute_instance_component_position; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""12.1.A Explicit Allocations - Use of the Transfer Capacity

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements is returned per XML response.

Params:
- document_type::String (required)
- business_type::String (required)
- contract_market_agreement_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- auction_category::String
- classification_sequence_attribute_instance_component_position::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function market121_a_explicit_allocations_use_of_the_transfer_capacity(_api::MarketApi, document_type::String, business_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; auction_category=nothing, classification_sequence_attribute_instance_component_position=nothing, _mediaType=nothing)
    _ctx = _oacinternal_market121_a_explicit_allocations_use_of_the_transfer_capacity(_api, document_type, business_type, contract_market_agreement_type, out_domain, in_domain, period_start, period_end; auction_category=auction_category, classification_sequence_attribute_instance_component_position=classification_sequence_attribute_instance_component_position, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function market121_a_explicit_allocations_use_of_the_transfer_capacity(_api::MarketApi, response_stream::Channel, document_type::String, business_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; auction_category=nothing, classification_sequence_attribute_instance_component_position=nothing, _mediaType=nothing)
    _ctx = _oacinternal_market121_a_explicit_allocations_use_of_the_transfer_capacity(_api, document_type, business_type, contract_market_agreement_type, out_domain, in_domain, period_start, period_end; auction_category=auction_category, classification_sequence_attribute_instance_component_position=classification_sequence_attribute_instance_component_position, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_market121_b_total_nominated_capacity_MarketApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_market121_b_total_nominated_capacity(_api::MarketApi, document_type::String, business_type::String, out_domain::String, in_domain::String, period_start::Int64; period_end=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_market121_b_total_nominated_capacity_MarketApi, "/market/12-1-b-total-nominated-capacity", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""12.1.B Total Nominated Capacity

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- business_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function market121_b_total_nominated_capacity(_api::MarketApi, document_type::String, business_type::String, out_domain::String, in_domain::String, period_start::Int64; period_end=nothing, _mediaType=nothing)
    _ctx = _oacinternal_market121_b_total_nominated_capacity(_api, document_type, business_type, out_domain, in_domain, period_start; period_end=period_end, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function market121_b_total_nominated_capacity(_api::MarketApi, response_stream::Channel, document_type::String, business_type::String, out_domain::String, in_domain::String, period_start::Int64; period_end=nothing, _mediaType=nothing)
    _ctx = _oacinternal_market121_b_total_nominated_capacity(_api, document_type, business_type, out_domain, in_domain, period_start; period_end=period_end, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_market121_c_total_capacity_already_allocated_MarketApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_market121_c_total_capacity_already_allocated(_api::MarketApi, document_type::String, business_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; auction_category=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_market121_c_total_capacity_already_allocated_MarketApi, "/market/12-1-c-total-capacity-already-allocated", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "contract_MarketAgreement.Type", contract_market_agreement_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "auction.Category", auction_category; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""12.1.C Total Capacity Already Allocated

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements is returned per XML response.

Params:
- document_type::String (required)
- business_type::String (required)
- contract_market_agreement_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- auction_category::String

Return: String, OpenAPI.Clients.ApiResponse
"""
function market121_c_total_capacity_already_allocated(_api::MarketApi, document_type::String, business_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; auction_category=nothing, _mediaType=nothing)
    _ctx = _oacinternal_market121_c_total_capacity_already_allocated(_api, document_type, business_type, contract_market_agreement_type, out_domain, in_domain, period_start, period_end; auction_category=auction_category, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function market121_c_total_capacity_already_allocated(_api::MarketApi, response_stream::Channel, document_type::String, business_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; auction_category=nothing, _mediaType=nothing)
    _ctx = _oacinternal_market121_c_total_capacity_already_allocated(_api, document_type, business_type, contract_market_agreement_type, out_domain, in_domain, period_start, period_end; auction_category=auction_category, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_market121_d_energy_prices_MarketApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_market121_d_energy_prices(_api::MarketApi, document_type::String, period_start::Int64, period_end::Int64, out_domain::String, in_domain::String; contract_market_agreement_type=nothing, classification_sequence_attribute_instance_component_position=nothing, offset=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_market121_d_energy_prices_MarketApi, "/market/12-1-d-energy-prices", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "contract_MarketAgreement.type", contract_market_agreement_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "classificationSequence_AttributeInstanceComponent.position", classification_sequence_attribute_instance_component_position; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""12.1.D Energy Prices

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements is returned per XML response. The `offset`parameter can be used to retrieve the data in batches of up to 100 TimeSeries, where `offset=0` returns the first 100 elements, `offset=100` returns the next 100, and so on.

Params:
- document_type::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- out_domain::String (required)
- in_domain::String (required)
- contract_market_agreement_type::String
- classification_sequence_attribute_instance_component_position::Int64
- offset::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function market121_d_energy_prices(_api::MarketApi, document_type::String, period_start::Int64, period_end::Int64, out_domain::String, in_domain::String; contract_market_agreement_type=nothing, classification_sequence_attribute_instance_component_position=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_market121_d_energy_prices(_api, document_type, period_start, period_end, out_domain, in_domain; contract_market_agreement_type=contract_market_agreement_type, classification_sequence_attribute_instance_component_position=classification_sequence_attribute_instance_component_position, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function market121_d_energy_prices(_api::MarketApi, response_stream::Channel, document_type::String, period_start::Int64, period_end::Int64, out_domain::String, in_domain::String; contract_market_agreement_type=nothing, classification_sequence_attribute_instance_component_position=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_market121_d_energy_prices(_api, document_type, period_start, period_end, out_domain, in_domain; contract_market_agreement_type=contract_market_agreement_type, classification_sequence_attribute_instance_component_position=classification_sequence_attribute_instance_component_position, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_market121_e_implicit_and_flow_based_allocations_congestion_income_MarketApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_market121_e_implicit_and_flow_based_allocations_congestion_income(_api::MarketApi, document_type::String, business_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_market121_e_implicit_and_flow_based_allocations_congestion_income_MarketApi, "/market/12-1-e-implicit-and-flow-based-allocations-congestion-income", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "contract_MarketAgreement.Type", contract_market_agreement_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""12.1.E Implicit and Flow-based Allocations - Congestion Income

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements is returned per XML response.

Params:
- document_type::String (required)
- business_type::String (required)
- contract_market_agreement_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function market121_e_implicit_and_flow_based_allocations_congestion_income(_api::MarketApi, document_type::String, business_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_market121_e_implicit_and_flow_based_allocations_congestion_income(_api, document_type, business_type, contract_market_agreement_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function market121_e_implicit_and_flow_based_allocations_congestion_income(_api::MarketApi, response_stream::Channel, document_type::String, business_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_market121_e_implicit_and_flow_based_allocations_congestion_income(_api, document_type, business_type, contract_market_agreement_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_market121_e_implicit_auction_net_positions_MarketApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_market121_e_implicit_auction_net_positions(_api::MarketApi, document_type::String, business_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_market121_e_implicit_auction_net_positions_MarketApi, "/market/12-1-e-implicit-auction-net-positions", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "businessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "contract_MarketAgreement.Type", contract_market_agreement_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""12.1.E Implicit Auction — Net Positions

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- business_type::String (required)
- contract_market_agreement_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function market121_e_implicit_auction_net_positions(_api::MarketApi, document_type::String, business_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_market121_e_implicit_auction_net_positions(_api, document_type, business_type, contract_market_agreement_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function market121_e_implicit_auction_net_positions(_api::MarketApi, response_stream::Channel, document_type::String, business_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; _mediaType=nothing)
    _ctx = _oacinternal_market121_e_implicit_auction_net_positions(_api, document_type, business_type, contract_market_agreement_type, out_domain, in_domain, period_start, period_end; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_market121_h_transfer_capacities_allocated_with_third_countries121_h_explicit_MarketApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_market121_h_transfer_capacities_allocated_with_third_countries121_h_explicit(_api::MarketApi, document_type::String, auction_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; auction_category=nothing, classification_sequence_attribute_instance_component_position=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_market121_h_transfer_capacities_allocated_with_third_countries121_h_explicit_MarketApi, "/market/12-1-h-transfer-capacities-allocated-with-third-countries-12-1-h-explicit", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "auction.Type", auction_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "contract_MarketAgreement.Type", contract_market_agreement_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "in_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "auction.Category", auction_category; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "classificationSequence_AttributeInstanceComponent.Position", classification_sequence_attribute_instance_component_position; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""12.1.H Transfer Capacities Allocated with Third Countries [12.1.H] (explicit)

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 TimeSeries elements is returned per XML response.

Params:
- document_type::String (required)
- auction_type::String (required)
- contract_market_agreement_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- auction_category::String
- classification_sequence_attribute_instance_component_position::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function market121_h_transfer_capacities_allocated_with_third_countries121_h_explicit(_api::MarketApi, document_type::String, auction_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; auction_category=nothing, classification_sequence_attribute_instance_component_position=nothing, _mediaType=nothing)
    _ctx = _oacinternal_market121_h_transfer_capacities_allocated_with_third_countries121_h_explicit(_api, document_type, auction_type, contract_market_agreement_type, out_domain, in_domain, period_start, period_end; auction_category=auction_category, classification_sequence_attribute_instance_component_position=classification_sequence_attribute_instance_component_position, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function market121_h_transfer_capacities_allocated_with_third_countries121_h_explicit(_api::MarketApi, response_stream::Channel, document_type::String, auction_type::String, contract_market_agreement_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; auction_category=nothing, classification_sequence_attribute_instance_component_position=nothing, _mediaType=nothing)
    _ctx = _oacinternal_market121_h_transfer_capacities_allocated_with_third_countries121_h_explicit(_api, document_type, auction_type, contract_market_agreement_type, out_domain, in_domain, period_start, period_end; auction_category=auction_category, classification_sequence_attribute_instance_component_position=classification_sequence_attribute_instance_component_position, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export market111_a_explicit_allocations_offered_transfer_capacity
export market111_b_flow_based_allocations
export market111_b_flow_based_allocations_archives
export market111_continuous_allocations_offered_transfer_capacity
export market111_implicit_allocations_offered_transfer_capacity
export market121_a_explicit_allocations_auction_revenue
export market121_a_explicit_allocations_use_of_the_transfer_capacity
export market121_b_total_nominated_capacity
export market121_c_total_capacity_already_allocated
export market121_d_energy_prices
export market121_e_implicit_and_flow_based_allocations_congestion_income
export market121_e_implicit_auction_net_positions
export market121_h_transfer_capacities_allocated_with_third_countries121_h_explicit
