# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct OutagesApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `OutagesApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ OutagesApi }) = "https://web-api.tp.entsoe.eu/api"

const _returntypes_outages101_a_b_unavailability_of_transmission_infrastructure_OutagesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_outages101_a_b_unavailability_of_transmission_infrastructure(_api::OutagesApi, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, doc_status=nothing, period_start_update=nothing, period_end_update=nothing, m_r_i_d=nothing, offset=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_outages101_a_b_unavailability_of_transmission_infrastructure_OutagesApi, "/outages/10-1-a-b-unavailability-of-transmission-infrastructure", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Out_Domain", out_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "In_Domain", in_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "BusinessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "DocStatus", doc_status; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "PeriodStartUpdate", period_start_update; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "PeriodEndUpdate", period_end_update; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "mRID", m_r_i_d; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""10.1.A&B Unavailability of Transmission Infrastructure

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.  - It applies to PeriodStart and PeriodEnd if PeriodStartUpdate and PeriodEndUpdate parameters are not included in the request.      - It applies only to PeriodStartUpdate and PeriodEndUpdate if included in the request.       <u><b>Response limit</b></u>: A maximum of 200 XML documents contained in the ZIP response. The `offset`parameter can be used to retrieve the data in batches of up to 200 XML documents, where `offset=0` returns the first 200 documents, `offset=200` returns the next 200, and so on.

Params:
- document_type::String (required)
- out_domain::String (required)
- in_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- business_type::String
- doc_status::String
- period_start_update::Int64
- period_end_update::Int64
- m_r_i_d::String
- offset::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function outages101_a_b_unavailability_of_transmission_infrastructure(_api::OutagesApi, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, doc_status=nothing, period_start_update=nothing, period_end_update=nothing, m_r_i_d=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_outages101_a_b_unavailability_of_transmission_infrastructure(_api, document_type, out_domain, in_domain, period_start, period_end; business_type=business_type, doc_status=doc_status, period_start_update=period_start_update, period_end_update=period_end_update, m_r_i_d=m_r_i_d, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function outages101_a_b_unavailability_of_transmission_infrastructure(_api::OutagesApi, response_stream::Channel, document_type::String, out_domain::String, in_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, doc_status=nothing, period_start_update=nothing, period_end_update=nothing, m_r_i_d=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_outages101_a_b_unavailability_of_transmission_infrastructure(_api, document_type, out_domain, in_domain, period_start, period_end; business_type=business_type, doc_status=doc_status, period_start_update=period_start_update, period_end_update=period_end_update, m_r_i_d=m_r_i_d, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_outages101_a_b_unavailability_of_transmission_infrastructure_available_capacity_OutagesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_outages101_a_b_unavailability_of_transmission_infrastructure_available_capacity(_api::OutagesApi, document_type::String, control_area_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, asset_registered_resource_m_r_i_d=nothing, doc_status=nothing, period_start_update=nothing, period_end_update=nothing, m_r_i_d=nothing, offset=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_outages101_a_b_unavailability_of_transmission_infrastructure_available_capacity_OutagesApi, "/outages/10-1-a-b-unavailability-of-transmission-infrastructure-available-capacity", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "ControlArea_Domain", control_area_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "BusinessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "Asset_RegisteredResource.mRID", asset_registered_resource_m_r_i_d; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "DocStatus", doc_status; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "PeriodStartUpdate", period_start_update; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "PeriodEndUpdate", period_end_update; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "mRID", m_r_i_d; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""10.1.A&B Unavailability of Transmission Infrastructure - Available Capacity

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.  - It applies to PeriodStart and PeriodEnd if PeriodStartUpdate and PeriodEndUpdate parameters are not included in the request.      - It applies only to PeriodStartUpdate and PeriodEndUpdate if included in the request.       <u><b>Response limit</b></u>: A maximum of 200 XML documents contained in the ZIP response. The `offset`parameter can be used to retrieve the data in batches of up to 200 XML documents, where `offset=0` returns the first 200 documents, `offset=200` returns the next 200, and so on.

Params:
- document_type::String (required)
- control_area_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- business_type::String
- asset_registered_resource_m_r_i_d::String
- doc_status::String
- period_start_update::Int64
- period_end_update::Int64
- m_r_i_d::String
- offset::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function outages101_a_b_unavailability_of_transmission_infrastructure_available_capacity(_api::OutagesApi, document_type::String, control_area_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, asset_registered_resource_m_r_i_d=nothing, doc_status=nothing, period_start_update=nothing, period_end_update=nothing, m_r_i_d=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_outages101_a_b_unavailability_of_transmission_infrastructure_available_capacity(_api, document_type, control_area_domain, period_start, period_end; business_type=business_type, asset_registered_resource_m_r_i_d=asset_registered_resource_m_r_i_d, doc_status=doc_status, period_start_update=period_start_update, period_end_update=period_end_update, m_r_i_d=m_r_i_d, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function outages101_a_b_unavailability_of_transmission_infrastructure_available_capacity(_api::OutagesApi, response_stream::Channel, document_type::String, control_area_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, asset_registered_resource_m_r_i_d=nothing, doc_status=nothing, period_start_update=nothing, period_end_update=nothing, m_r_i_d=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_outages101_a_b_unavailability_of_transmission_infrastructure_available_capacity(_api, document_type, control_area_domain, period_start, period_end; business_type=business_type, asset_registered_resource_m_r_i_d=asset_registered_resource_m_r_i_d, doc_status=doc_status, period_start_update=period_start_update, period_end_update=period_end_update, m_r_i_d=m_r_i_d, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_outages101_a_b_unavailability_of_transmission_infrastructure_net_position_impact_OutagesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_outages101_a_b_unavailability_of_transmission_infrastructure_net_position_impact(_api::OutagesApi, document_type::String, p_t_d_f_domain_m_r_i_d::String, period_start::Int64, period_end::Int64; business_type=nothing, doc_status=nothing, period_start_update=nothing, period_end_update=nothing, m_r_i_d=nothing, offset=nothing, asset_registered_resource_m_r_i_d=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_outages101_a_b_unavailability_of_transmission_infrastructure_net_position_impact_OutagesApi, "/outages/10-1-a-b-unavailability-of-transmission-infrastructure-net-position-impact", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "pTDF_Domain.mRID", p_t_d_f_domain_m_r_i_d; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "BusinessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "DocStatus", doc_status; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "PeriodStartUpdate", period_start_update; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "PeriodEndUpdate", period_end_update; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "mRID", m_r_i_d; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "Asset_RegisteredResource.mRID", asset_registered_resource_m_r_i_d; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""10.1.A&B Unavailability of Transmission Infrastructure  - Net Position Impact

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.  - It applies to PeriodStart and PeriodEnd if PeriodStartUpdate and PeriodEndUpdate parameters are not included in the request.      - It applies only to PeriodStartUpdate and PeriodEndUpdate if included in the request.       <u><b>Response limit</b></u>: A maximum of 200 XML documents contained in the ZIP response. The `offset`parameter can be used to retrieve the data in batches of up to 200 XML documents, where `offset=0` returns the first 200 documents, `offset=200` returns the next 200, and so on.

Params:
- document_type::String (required)
- p_t_d_f_domain_m_r_i_d::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- business_type::String
- doc_status::String
- period_start_update::Int64
- period_end_update::Int64
- m_r_i_d::String
- offset::Int64
- asset_registered_resource_m_r_i_d::String

Return: String, OpenAPI.Clients.ApiResponse
"""
function outages101_a_b_unavailability_of_transmission_infrastructure_net_position_impact(_api::OutagesApi, document_type::String, p_t_d_f_domain_m_r_i_d::String, period_start::Int64, period_end::Int64; business_type=nothing, doc_status=nothing, period_start_update=nothing, period_end_update=nothing, m_r_i_d=nothing, offset=nothing, asset_registered_resource_m_r_i_d=nothing, _mediaType=nothing)
    _ctx = _oacinternal_outages101_a_b_unavailability_of_transmission_infrastructure_net_position_impact(_api, document_type, p_t_d_f_domain_m_r_i_d, period_start, period_end; business_type=business_type, doc_status=doc_status, period_start_update=period_start_update, period_end_update=period_end_update, m_r_i_d=m_r_i_d, offset=offset, asset_registered_resource_m_r_i_d=asset_registered_resource_m_r_i_d, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function outages101_a_b_unavailability_of_transmission_infrastructure_net_position_impact(_api::OutagesApi, response_stream::Channel, document_type::String, p_t_d_f_domain_m_r_i_d::String, period_start::Int64, period_end::Int64; business_type=nothing, doc_status=nothing, period_start_update=nothing, period_end_update=nothing, m_r_i_d=nothing, offset=nothing, asset_registered_resource_m_r_i_d=nothing, _mediaType=nothing)
    _ctx = _oacinternal_outages101_a_b_unavailability_of_transmission_infrastructure_net_position_impact(_api, document_type, p_t_d_f_domain_m_r_i_d, period_start, period_end; business_type=business_type, doc_status=doc_status, period_start_update=period_start_update, period_end_update=period_end_update, m_r_i_d=m_r_i_d, offset=offset, asset_registered_resource_m_r_i_d=asset_registered_resource_m_r_i_d, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_outages101_c_unavailability_of_offshore_grid_infrastructure_OutagesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_outages101_c_unavailability_of_offshore_grid_infrastructure(_api::OutagesApi, document_type::String, bidding_zone_domain::String, period_start::Int64, period_end::Int64; doc_status=nothing, period_start_update=nothing, period_end_update=nothing, m_r_i_d=nothing, offset=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_outages101_c_unavailability_of_offshore_grid_infrastructure_OutagesApi, "/outages/10-1-c-unavailability-of-offshore-grid-infrastructure", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "BiddingZone_Domain", bidding_zone_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "DocStatus", doc_status; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "PeriodStartUpdate", period_start_update; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "PeriodEndUpdate", period_end_update; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "mRID", m_r_i_d; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""10.1.C Unavailability of Offshore Grid Infrastructure

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.  - It applies to PeriodStart and PeriodEnd if PeriodStartUpdate and PeriodEndUpdate parameters are not included in the request.      - It applies only to PeriodStartUpdate and PeriodEndUpdate if included in the request.       <u><b>Response limit</b></u>: A maximum of 200 XML documents contained in the ZIP response. The `offset`parameter can be used to retrieve the data in batches of up to 200 XML documents, where `offset=0` returns the first 200 documents, `offset=200` returns the next 200, and so on.

Params:
- document_type::String (required)
- bidding_zone_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- doc_status::String
- period_start_update::Int64
- period_end_update::Int64
- m_r_i_d::String
- offset::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function outages101_c_unavailability_of_offshore_grid_infrastructure(_api::OutagesApi, document_type::String, bidding_zone_domain::String, period_start::Int64, period_end::Int64; doc_status=nothing, period_start_update=nothing, period_end_update=nothing, m_r_i_d=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_outages101_c_unavailability_of_offshore_grid_infrastructure(_api, document_type, bidding_zone_domain, period_start, period_end; doc_status=doc_status, period_start_update=period_start_update, period_end_update=period_end_update, m_r_i_d=m_r_i_d, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function outages101_c_unavailability_of_offshore_grid_infrastructure(_api::OutagesApi, response_stream::Channel, document_type::String, bidding_zone_domain::String, period_start::Int64, period_end::Int64; doc_status=nothing, period_start_update=nothing, period_end_update=nothing, m_r_i_d=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_outages101_c_unavailability_of_offshore_grid_infrastructure(_api, document_type, bidding_zone_domain, period_start, period_end; doc_status=doc_status, period_start_update=period_start_update, period_end_update=period_end_update, m_r_i_d=m_r_i_d, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_outages151_a_b_unavailability_of_generation_units_OutagesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_outages151_a_b_unavailability_of_generation_units(_api::OutagesApi, document_type::String, bidding_zone_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, doc_status=nothing, period_start_update=nothing, period_end_update=nothing, registered_resource=nothing, m_r_i_d=nothing, offset=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_outages151_a_b_unavailability_of_generation_units_OutagesApi, "/outages/15-1-a-b-unavailability-of-generation-units", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "BiddingZone_Domain", bidding_zone_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "BusinessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "DocStatus", doc_status; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "PeriodStartUpdate", period_start_update; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "PeriodEndUpdate", period_end_update; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "RegisteredResource", registered_resource; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "mRID", m_r_i_d; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""15.1.A&B Unavailability of Generation Units

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.  - It applies to PeriodStart and PeriodEnd if PeriodStartUpdate and PeriodEndUpdate parameters are not included in the request.      - It applies only to PeriodStartUpdate and PeriodEndUpdate if included in the request.       <u><b>Response limit</b></u>: A maximum of 200 XML documents contained in the ZIP response. The `offset`parameter can be used to retrieve the data in batches of up to 200 XML documents, where `offset=0` returns the first 200 documents, `offset=200` returns the next 200, and so on.

Params:
- document_type::String (required)
- bidding_zone_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- business_type::String
- doc_status::String
- period_start_update::Int64
- period_end_update::Int64
- registered_resource::String
- m_r_i_d::String
- offset::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function outages151_a_b_unavailability_of_generation_units(_api::OutagesApi, document_type::String, bidding_zone_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, doc_status=nothing, period_start_update=nothing, period_end_update=nothing, registered_resource=nothing, m_r_i_d=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_outages151_a_b_unavailability_of_generation_units(_api, document_type, bidding_zone_domain, period_start, period_end; business_type=business_type, doc_status=doc_status, period_start_update=period_start_update, period_end_update=period_end_update, registered_resource=registered_resource, m_r_i_d=m_r_i_d, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function outages151_a_b_unavailability_of_generation_units(_api::OutagesApi, response_stream::Channel, document_type::String, bidding_zone_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, doc_status=nothing, period_start_update=nothing, period_end_update=nothing, registered_resource=nothing, m_r_i_d=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_outages151_a_b_unavailability_of_generation_units(_api, document_type, bidding_zone_domain, period_start, period_end; business_type=business_type, doc_status=doc_status, period_start_update=period_start_update, period_end_update=period_end_update, registered_resource=registered_resource, m_r_i_d=m_r_i_d, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_outages151_c_d_unavailability_of_production_units_OutagesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_outages151_c_d_unavailability_of_production_units(_api::OutagesApi, document_type::String, bidding_zone_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, doc_status=nothing, period_start_update=nothing, period_end_update=nothing, registered_resource=nothing, m_r_i_d=nothing, offset=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_outages151_c_d_unavailability_of_production_units_OutagesApi, "/outages/15-1-c-d-unavailability-of-production-units", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "BiddingZone_Domain", bidding_zone_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "BusinessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "DocStatus", doc_status; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "PeriodStartUpdate", period_start_update; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "PeriodEndUpdate", period_end_update; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "RegisteredResource", registered_resource; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "mRID", m_r_i_d; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""15.1.C-D Unavailability of Production Units

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.  - It applies to PeriodStart and PeriodEnd if PeriodStartUpdate and PeriodEndUpdate parameters are not included in the request.      - It applies only to PeriodStartUpdate and PeriodEndUpdate if included in the request.       <u><b>Response limit</b></u>: A maximum of 200 XML documents contained in the ZIP response. The `offset`parameter can be used to retrieve the data in batches of up to 200 XML documents, where `offset=0` returns the first 200 documents, `offset=200` returns the next 200, and so on.

Params:
- document_type::String (required)
- bidding_zone_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- business_type::String
- doc_status::String
- period_start_update::Int64
- period_end_update::Int64
- registered_resource::String
- m_r_i_d::String
- offset::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function outages151_c_d_unavailability_of_production_units(_api::OutagesApi, document_type::String, bidding_zone_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, doc_status=nothing, period_start_update=nothing, period_end_update=nothing, registered_resource=nothing, m_r_i_d=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_outages151_c_d_unavailability_of_production_units(_api, document_type, bidding_zone_domain, period_start, period_end; business_type=business_type, doc_status=doc_status, period_start_update=period_start_update, period_end_update=period_end_update, registered_resource=registered_resource, m_r_i_d=m_r_i_d, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function outages151_c_d_unavailability_of_production_units(_api::OutagesApi, response_stream::Channel, document_type::String, bidding_zone_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, doc_status=nothing, period_start_update=nothing, period_end_update=nothing, registered_resource=nothing, m_r_i_d=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_outages151_c_d_unavailability_of_production_units(_api, document_type, bidding_zone_domain, period_start, period_end; business_type=business_type, doc_status=doc_status, period_start_update=period_start_update, period_end_update=period_end_update, registered_resource=registered_resource, m_r_i_d=m_r_i_d, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_outages71_a_b_aggregated_unavailability_of_consumption_units_OutagesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_outages71_a_b_aggregated_unavailability_of_consumption_units(_api::OutagesApi, document_type::String, bidding_zone_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_outages71_a_b_aggregated_unavailability_of_consumption_units_OutagesApi, "/outages/7-1-a-b-aggregated-unavailability-of-consumption-units", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "BiddingZone_Domain", bidding_zone_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "BusinessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""7.1.A-B Aggregated Unavailability of Consumption Units

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.

Params:
- document_type::String (required)
- bidding_zone_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- business_type::String

Return: String, OpenAPI.Clients.ApiResponse
"""
function outages71_a_b_aggregated_unavailability_of_consumption_units(_api::OutagesApi, document_type::String, bidding_zone_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_outages71_a_b_aggregated_unavailability_of_consumption_units(_api, document_type, bidding_zone_domain, period_start, period_end; business_type=business_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function outages71_a_b_aggregated_unavailability_of_consumption_units(_api::OutagesApi, response_stream::Channel, document_type::String, bidding_zone_domain::String, period_start::Int64, period_end::Int64; business_type=nothing, _mediaType=nothing)
    _ctx = _oacinternal_outages71_a_b_aggregated_unavailability_of_consumption_units(_api, document_type, bidding_zone_domain, period_start, period_end; business_type=business_type, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_outages_fall_backs_ifs_in72_mfrr311_afrr310_OutagesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_outages_fall_backs_ifs_in72_mfrr311_afrr310(_api::OutagesApi, document_type::String, process_type::String, business_type::String, bidding_zone_domain::String, period_start::Int64, period_end::Int64; doc_status=nothing, m_r_i_d=nothing, offset=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_outages_fall_backs_ifs_in72_mfrr311_afrr310_OutagesApi, "/outages/fall-backs-ifs-in-7-2-mfrr-3-11-afrr-3-10", ["SecurityToken", ])
    OpenAPI.Clients.set_param(_ctx.query, "documentType", document_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "ProcessType", process_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "BusinessType", business_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "BiddingZone_Domain", bidding_zone_domain; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "periodStart", period_start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "periodEnd", period_end; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "DocStatus", doc_status; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "mRID", m_r_i_d; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "offset", offset; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Fall-backs [IFs IN 7.2, mFRR 3.11, aFRR 3.10]

<u><b>Request limit:</b></u> Each request may cover a period of up to 1 year.   <u><b><br>Response limit</b></u>: A maximum of 100 XML documents contained in the ZIP response. The `offset`parameter can be used to retrieve the data in batches of up to 100 XML documents, where `offset=0` returns the first 100 documents, `offset=100` returns the next 100, and so on.

Params:
- document_type::String (required)
- process_type::String (required)
- business_type::String (required)
- bidding_zone_domain::String (required)
- period_start::Int64 (required)
- period_end::Int64 (required)
- doc_status::String
- m_r_i_d::String
- offset::Int64

Return: String, OpenAPI.Clients.ApiResponse
"""
function outages_fall_backs_ifs_in72_mfrr311_afrr310(_api::OutagesApi, document_type::String, process_type::String, business_type::String, bidding_zone_domain::String, period_start::Int64, period_end::Int64; doc_status=nothing, m_r_i_d=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_outages_fall_backs_ifs_in72_mfrr311_afrr310(_api, document_type, process_type, business_type, bidding_zone_domain, period_start, period_end; doc_status=doc_status, m_r_i_d=m_r_i_d, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function outages_fall_backs_ifs_in72_mfrr311_afrr310(_api::OutagesApi, response_stream::Channel, document_type::String, process_type::String, business_type::String, bidding_zone_domain::String, period_start::Int64, period_end::Int64; doc_status=nothing, m_r_i_d=nothing, offset=nothing, _mediaType=nothing)
    _ctx = _oacinternal_outages_fall_backs_ifs_in72_mfrr311_afrr310(_api, document_type, process_type, business_type, bidding_zone_domain, period_start, period_end; doc_status=doc_status, m_r_i_d=m_r_i_d, offset=offset, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export outages101_a_b_unavailability_of_transmission_infrastructure
export outages101_a_b_unavailability_of_transmission_infrastructure_available_capacity
export outages101_a_b_unavailability_of_transmission_infrastructure_net_position_impact
export outages101_c_unavailability_of_offshore_grid_infrastructure
export outages151_a_b_unavailability_of_generation_units
export outages151_c_d_unavailability_of_production_units
export outages71_a_b_aggregated_unavailability_of_consumption_units
export outages_fall_backs_ifs_in72_mfrr311_afrr310
