# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

module EntsoEAPI

using Dates, TimeZones
using OpenAPI
using OpenAPI.Clients

const API_VERSION = "1.0.0"

include("modelincludes.jl")

include("apis/api_BalancingApi.jl")
include("apis/api_GenerationApi.jl")
include("apis/api_LoadApi.jl")
include("apis/api_MarketApi.jl")
include("apis/api_MasterDataApi.jl")
include("apis/api_OMIApi.jl")
include("apis/api_OutagesApi.jl")
include("apis/api_TransmissionApi.jl")

# export models

# export operations
export BalancingApi
export GenerationApi
export LoadApi
export MarketApi
export MasterDataApi
export OMIApi
export OutagesApi
export TransmissionApi

end # module EntsoEAPI
